### ISSUE TITLE
is sample source work?

### ISSUE THREAD

**Issue by leeyc09** [wordpress-mobile/WordPress-Editor-Android#1]
has a lot of bug.
different package name, can not find import files, etc..
is sample source work?

**Comment by kanilturgut** [comment]
I don't think it works. When I try to import, it always says "Error:Configuration with name 'debug' not found.''

**Comment by maxme** [comment]
The project is no ready yet, we're going to publish maven artefacts for dependencies (utils and analytics) to avoid these kind of issues during build.
