### ISSUE TITLE
Format bar (phone)

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#10]
On the iOS editor, the iPhone format bar buttons were updated to the following:

![screen shot 2015-03-30 at 11 09 00 am](https://cloud.githubusercontent.com/assets/154014/6900631/7478c69e-d6cd-11e4-9ff9-27b8967b9444.png)

This was a completely data-driven decision based on usage metrics. Not sure if Android users will have different needs, but we should find out. Also note how the layouts differ between tablet and phone.

For context, the current editor has the following:

![screen shot 2015-03-30 at 10 57 33 am](https://cloud.githubusercontent.com/assets/154014/6900664/9c1f86ce-d6cd-11e4-9849-f1fa121ce227.png)

/cc @thinahlu @meremagee

**Comment by aforcier** [comment]
Some notes:
- As on iOS, the HTML button should always be visible, while the rest of the buttons scroll (if needed).
- If not scrolling, buttons should be evenly spaced.
- On iOS, the format bar icons gray out (except for the HTML button) when editing the title

**Comment by bummytime** [comment]
Another note, if a hardware keyboard is being used, format bar should be placed at the bottom of the screen (assuming the soft keyboard is not displayed).

**Comment by thianhlu** [comment]
@thianhlu 

Do review on icons and match material design enabled/disabled states

**Comment by thianhlu** [comment]
lets leave buttons and disabled button state the same as iOS.

We could however add a slight animation for tapping buttons, https://cloudup.com/cb2NTJ_8DxQ, which could help provide a bit more visual feedback but could be overkill.

**Comment by aforcier** [comment]
Most of the buttons aren't hooked up to anything yet, but here's a first look at the re-styled format bar on Android (phone-sized):

![2015-04-17-format-bar-preview-cropped-full](https://cloud.githubusercontent.com/assets/9613966/7204747/a368609e-e4f2-11e4-9063-f2c57676522b.png)

cc @thianhlu

**Comment by aforcier** [comment]
And here it is with the less flattering Jelly Bean default keyboard:

![api17-format-bar](https://cloud.githubusercontent.com/assets/9613966/7205407/20a86762-e4f7-11e4-9608-6e57ccbcd60d.png)

cc @thianhlu

**Comment by thianhlu** [comment]
Dumb question @aforcier. What's the OS usage for our android devices? Are most people on Lollipop or Kitkat at this point? How does it look on those default keyboards?

**Comment by meremagee** [comment]
According to a few sources, it looks like Kitkat still rules the Android market with about 40% android usage https://developer.android.com/about/dashboards/index.html. This lines up well w/ app usage data.

![](https://cloudup.com/c9XVCVoK19V+)

Here's a broad look at screen size. I can look into more specific dimensions, too. (More specs around size & pixel density guidelines [here](https://developer.android.com/guide/practices/screens_support.html))

![](https://cloudup.com/cwazWjGsx5B+)

**Comment by aforcier** [comment]
@thianhlu about 75% are on Kit Kat or earlier, and will have a dark keyboard.

**Comment by bummytime** [comment]
Yeah, @thianhlu, like @meremagee showed above Lollipop usage is extremely low. And if past history is any guide we can expect ICS, Jelly Bean, and KitKat to be around for the foreseeable future.

Just for context...here is ICS and Jelly Bean:

![screen shot 2015-04-17 at 11 43 54 am](https://cloud.githubusercontent.com/assets/154014/7206455/3c664988-e4f7-11e4-8154-8977b00dc5d0.png)

![screen shot 2015-04-17 at 11 43 24 am](https://cloud.githubusercontent.com/assets/154014/7206465/522b417e-e4f7-11e4-9a4d-577a6da0e937.png)

Lollipop:

![nexus2cee-image36](https://cloud.githubusercontent.com/assets/154014/7206459/46df8a50-e4f7-11e4-80ac-3cbad245383e.png)

Also note that it is **very** common for peeps/handset manufacturers to install different keyboards as well. Counting on a specific color scheme might not be the best program...

**Comment by thianhlu** [comment]
@thianhlu try out format bar with dark bg and dark keyboard
