### ISSUE TITLE
Post list: List can be empty after changing blogs with no internet connection.

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#100]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/199

Edge case. 

Be in airplane mode and have multiple blogs in the app. 
Tap to change blogs to a blog you have not previously synced. 
Immediately you see the no connectivity prompt when the post list tried to refresh. (Maybe it would be better to fail silently in this case.)
Dismiss the prompt and notice that the post list is completely empty, but the detail still shows the detail of the selected post of the previous blog. 

2.5 beta 4(?) / Nexus 7

**Comment by rachelmcr** [comment]
I retested this issue in alpha-4 with these results:

When you switch to another blog, you see a "No Connection" message at the bottom of the screen:

![2016-03-21 17 55 44](https://cloud.githubusercontent.com/assets/8658164/13928650/8289f336-ef8e-11e5-86fc-683db0d98746.png)

In the post list, you get a "There is no network available" error message. No posts are loaded/displayed. The same message pops up if you try to refresh the screen without an error:

![2016-03-21 17 55 49](https://cloud.githubusercontent.com/assets/8658164/13928668/90be56cc-ef8e-11e5-99cd-66c862d0df85.png)

Closing this issue as resolved.
