### ISSUE TITLE
Can't remove a featured image from a post

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#102]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/169

Currently you can't remove a featured image from a post, only add. Perhaps we should make it more like WPiOS where there is a separate section in the post editor for adding/updating/removing a featured image.

**Comment by maxme** [comment]
Should be fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/2500
