### ISSUE TITLE
Add support for lists in the post editor

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#104]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/135

Users have requested that we add support for ordered and unordered lists in the editor.

**Comment by rachelmcr** [comment]
The new editor supports both ordered and unordered lists with a formatting button. Closing as this is resolved in the new editor.

Checked on Nexus 9, Android 6.0.1, alpha-4.
