### ISSUE TITLE
Image caption appears in the editor after rotating.

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#105]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/110

These are the steps I took, some may not be necessary:
Create a new post
In the editor add an image, then add another image.
Tap the first image and make it featured and include in content, and give it a caption.
Tap the second image and give it a caption.
Rotate the device.
The caption of the second image is now included in the post content.

**Comment by rachelmcr** [comment]
I can't reproduce this issue in the new editor. I tried the steps above, and some other tests with captions. Each time, the caption appears below the corresponding image as a caption and doesn't move into the body of the post.

Tested on Nexus 9, Android 6.0.1, alpha-4.
