### ISSUE TITLE
Change text color?

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#106]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/109

A user has requested that the app allow changing of the text color in posts/pages.

**Comment by rachelmcr** [comment]
Just a quick note that as of version alpha-4 the new editor does not include a text color formatting button. Current formatting buttons include:
- bold
- italics
- strikethrough
- unordered list
- ordered list
- blockquote

**Comment by aforcier** [comment]
This would have to be added as part of an overall overhaul of the format bar; the decision was to keep a small number of high-usage formatting options to refine the mobile editor experience.

There are no plans to change this now, but if in the future we decide to add an 'advanced' option with more format buttons, we'd be considering all options available on WordPress and prioritize by usage.
