### ISSUE TITLE
Custom image link URLs

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#107]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/108

Perhaps another field to the image settings could be added for a custom link. User request.

**Comment by rachelmcr** [comment]
The new editor includes a custom link field in the image settings after adding an image to a post. Checked in version alpha-4:

![2016-03-21 14 42 38](https://cloud.githubusercontent.com/assets/8658164/13922240/50c2a62e-ef73-11e5-8624-045b79ee5b82.png)

Closing as resolved.
