### ISSUE TITLE
Images in previews try to open externally.

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#108]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/98

Nexus 7, 4.2.2
Go to a post preview that has an image. 
Tap the image.
You should be prompted to open the image in an external application.
We should probably just show this in-app.

**Comment by rachelmcr** [comment]
I tested with the steps above and couldn't reproduce the issue. When I tap on the image, it opens the image link in-app instead of trying to open it externally. Closing as resolved.

Tested on Nexus 9, Android 6.0.1, alpha-4.
