### ISSUE TITLE
Featured images on pages are broken.

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#109]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/83

Edit a page
Add an image. 
Tap the image and check the option to use it as a featured image. Do not check the option to include the image in the content. 
Publish the page. 
An image tag for the featured image is included in the post body even though you did not check the option to do this.
The image tag is missing a src attribute, and has android-uri="content:// ... " instead.

**Comment by rachelmcr** [comment]
I re-tested featured images on pages in the new editor. I was able to add a featured image without any issues there. (Note that the second option to include the image in the content is no longer in the new editor. Instead, you can add a featured image from the post/page settings or add it to the post/page body and also set it as a featured image from the image settings.) Closing as resolved.

Tested in Nexus 9, Android 6.0.1, alpha-4.
