### ISSUE TITLE
HTML mode

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#11]
What pairs nicely with a new 100% visual editor? Why, an HTML mode of course. On iOS we have this:

![scaled screen shot 2015-03-30 at 2 36 55 pm](https://cloud.githubusercontent.com/assets/154014/6904990/51567eb4-d6ea-11e4-8c6d-b4bf8df7cc8d.png)

![scaled screen shot 2015-03-30 at 2 38 53 pm](https://cloud.githubusercontent.com/assets/154014/6905010/8a1cb6b4-d6ea-11e4-8a74-5303c4b6e842.png)

Things to consider:
- Paragraph formatting - show spaces instead of `<p>`'s. (Should be handed [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/3fb089aec656f99e35447ca21ace89eea254181a/Assets/wpsave.js) and [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/3fb089aec656f99e35447ca21ace89eea254181a/Assets/wpload.js).)
- Fontface (Menlo-Regular 14pt on iOS)
- Tag and element colors
- Post title positioned in the same place as when in visual mode (with the same font...Merriweather)
- Format bar button should act as a toggle between modes

@thinahlu can offer up more specifics if he wants.

Ref: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/110
and https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/154

**Comment by aforcier** [comment]
I ran into a difference in how the current iOS editor and the legacy Android editor handle formatting in HTML mode that I'd like some input on.

Here is how applying formatting with no text selected works on each.

iOS: https://cloudup.com/c_D1PfneupY
- Press format button
- Opening and closing tags are inserted simultaneously
- Format button is immediately un-highlighted
- Cursor is placed at the end of the closing tag, and you have to move the cursor back to between the tags to type your text that should be formatted

Android (legacy): https://cloudup.com/coR6KC0HIzz
- Press format button
- Opening tag only is inserted
- Format button is now highlighted
- Cursor is placed at the end of the opening tag, ready for text to be inserted and formatted right away
- When finished, press format bar button again
- Closing tag is inserted, and the button is un-highlighted

My vote would be to keep the legacy Android method for the new editor. What do you think @bummytime @meremagee @thianhlu?

**Comment by bummytime** [comment]
> My vote would be to keep the legacy Android method for the new editor. 

@aforcier I agree with you.

**Comment by meremagee** [comment]
I agree as well, given the assumption is that anyone who prefers to use HTML is familiar enough with the syntax that they'd close the tag deliberately. This also allows us to compare usage between OS and see if we shouldn't adapt one or the other.
