### ISSUE TITLE
Custom post types, custom taxonomies, and custom fields

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#114]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/63

It would be extremely useful if Wordpress for Android supported custom post types, custom taxonomies, and custom fields. I would like to formally request that the functionality be added.

**Comment by rachelmcr** [comment]
A user requested custom post types in a recent app review:

> I really like how it looks, the UI got better. The support guys are awesome. But still needs the custom post compatibility.

**Comment by BigActual** [comment]
A client requested the ability to edit CPTs using the app. Found this thread in the process of troubleshooting. Any progress on this issue?

**Comment by catehstn** [comment]
They're on the radar but not currently being worked on.

**Comment by sarahblackstock** [comment]
User in 4-star app review requested custom post types be added to the app.

**Comment by sarahdenise** [comment]
+1

**Comment by rachelmcr** [comment]
This repo is deprecated, so I'm closing this issue and reopening the original issue to track this request: https://github.com/wordpress-mobile/WordPress-Android/issues/63
