### ISSUE TITLE
Add ability Search Posts, Pages and Comments

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#115]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/62

The only way to search the content is to go the the browser and search the site. Would be convenient to search within the app.

**Comment by rachelmcr** [comment]
This isn't really an editor issue — since it's about searching posts/pages/comments it's more about the Blog Posts list, the Pages list, and the Comments list rather than the editor, so I'm going to reopen the original issue and close this one.
