### ISSUE TITLE
Problem with article source code

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#116]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/61

I'm using the source code view in my blog when writing new articles. The problem is that the WordPress Android app does have such a mode. So when I write new articles or edit older articles it adds line breaks "<br />" etc. automatically when saving the article. Please add a "source only" edit mode to the app which does not automatically add HTML tags.

**Comment by rachelmcr** [comment]
This should be resolved with the visual/html modes in the new editor, since you can edit directly in HTML mode now. I haven't had any issues with extra line breaks, etc. added in the new editor (as of version alpha-4).

**Comment by rachelmcr** [comment]
I haven't encountered this issue in further testing of the visual editor (as of alpha-6) so I'm closing this issue as resolved.
