### ISSUE TITLE
Media: Support uploading arbitrary files

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#117]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/59

Wordpress allows uploading arbitrary files if correctly configured.
If the android app allowed that too, one could upload gpx tracks and have them visualized by the gp2graphics plugin for wordpress!
Add another item in the media choose dialog that lets users choose a file with a file manager (if installed).

**Comment by thejeshgn** [comment]
+1 Audio is a big feature for mobile bloggers.

**Comment by rachelmcr** [comment]
A beta tester [recently requested](https://plus.google.com/u/0/+JohnXenzirrilCalderon/posts/guZFz3rP5Lr) audio uploads:

> Will there ever be support for upload of Audio files via the App?  I use my Wordpress to Podcast, but I always have to go to the Mobile Web to do any audio uploading.  Would love to be able to add audio via the app.

**Comment by aforcier** [comment]
Also a request for PDFs (and documents in general):

> A user requested the option to upload documents (e.g. PDF files) to the media library in the app.
> 
> I found that I can access PDF files on my device, for example, by selecting "Select a photo from gallery" and then choosing Dropbox -> "Show all file types." It looks like the file is being uploaded (and added to the post if it's added through the editor) but nothing is actually uploaded to the media library.
> 
> Requested in Helpshift issue 70628.

(added from #271)

**Comment by rachelmcr** [comment]
A user left an app review requesting support for mp3 uploads:

> Please enable mp3 upload from mobile to media for users who have the feature !!!

**Comment by rachelmcr** [comment]
We received another request (via an app review) for uploading documents in general.

**Comment by KokkieH** [comment]
Received another request to upload audio files via [Twitter](https://twitter.com/user/status/784980476008079360).

**Comment by rachelmcr** [comment]
Audio uploads were requested again by a user in 137151-h.

**Comment by rachelmcr** [comment]
We had another request for PDF and document uploads in an app review:

> Application simple d'utilisation fait correctement son job. Mais il y a tout de même un problème il est impossible d'uploader  un fichier pdf ou word etc... Il n'y a que des options pour les images et pourtant sur le site tout est ok. Je remettrai les deux  étoiles lorsque vous résoudrerais cela

Google translation:

> single use application doing its job. But there is still a problem it is not possible to upload a pdf or word etc ... There are only options for images, yet on the whole site is ok. I will give the two stars when it résoudrerais

**Comment by rachelmcr** [comment]
Another app review requested support for uploading more file types:

> Coba ditambah ekstensi di media ... .mp3 , .wav .pdf . Word ... biar post tautan kebih laluasa

Google translation:

> Try plus extensions in the media ... .mp3, .wav .pdf. Word ... let me post the link kebih laluasa

**Comment by rachelmcr** [comment]
Since this isn't editor specific (we could support arbitrary file uploads in the Media settings as well) I'm closing this issue in favor of this one: https://github.com/wordpress-mobile/WordPress-Android/issues/4842
