### ISSUE TITLE
Cursor in title field and keyboard up on new posts

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#120]
On new posts, make sure the cursor is in the title field and keyboard is up ready to go! (For an example of this behavior, check out Evernote Android or WPiOS).

**Comment by bummytime** [comment]
Also, lets do the same thing for existing posts.

**Comment by thianhlu** [comment]
Has this been fixed? If not, title is not in focus upon new post/edit post.

**Comment by aforcier** [comment]
@thianhlu there was a PR that addressed it but it ran into a lot of issues on API<19 so it was put on hold for the time being: https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/126

**Comment by bummytime** [comment]
From #235:

> Found yet another new related bug (sorry!). This one happens when visiting the home screen and then re-opening the app, under certain circumstances.
> 
> On a phone that doesn't rotate the home screen when in landscape mode:
> - Launch example app, and open the editor
> - In landscape mode, tap the content so that the keyboard appears and the action bar hides (this bug doesn't occur if the keyboard is down)
> - Go to home screen (it'll be in portrait mode, while you're still holding the phone in landscape - keep it like that)
> - Re-launch the editor
> - You'll see the editor screen, with no keyboard and no ActionBar
> 
> This seems not to happen on devices that rotate the home screen (which is all the tablets I tested, and for some reason API15 emulator).

**Comment by rachelmcr** [comment]
A couple testers have noticed that the editor doesn't have focus when you start a new post. In addition, it causes some issues if you try to start adding content right away:
- Tap the media icon and you can select media to upload, but it isn't inserted into the post.
- Tap the link icon and you can enter a link and link text, but it isn't inserted into the post.
- You can tap the other formatting buttons and they are highlighted blue, but the editor doesn't gain focus. If you then tap into the editor and start typing, the button stays highlighted but isn't actually active.

Testers:
- Donncha, Galaxy S5, Marshmallow 6.0.1 (CM 13.0)
- Mo, Moto X 2, Android 6.0
- Me, Nexus 9, Android 6.0.1

**Comment by aforcier** [comment]
I'm assigning this issue to the `1.0` (release) milestone. I think at the very least we can apply @bummytime's original fix for newer versions (`API19`+) for now, and get to older APIs in the future.
