### ISSUE TITLE
Unable to apply style mid-typing (autocorrect, API19+)

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#123]
Currently, applying a style (e.g. bold) while typing a word (i.e., not right after a space or line break) doesn't work on software keyboards on API 19+. This seems to be an issue with how Android's autocorrect behaves inside an API 19+ Chromium `WebView`.

Notes:
- This is not an issue on API 18 and lower. In fact, API 18 (and probably lower also) displays suggestions correctly even as formatting is applied
- A possible workaround involves selectively disabling autocorrect when applying styling mid-word. However, this approach only works for `API>17`, and doesn't work for IME keyboards or the Swype keyboard (most likely others as well).

**Comment by aforcier** [comment]
The `test-bold-input` branch has a partial demo of the workaround.

**Comment by bummytime** [comment]
Tested: also fails on Samsung S6 (API 21)

**Comment by thianhlu** [comment]
Other downsides are trying to apply additional styles mid-word or removing styles mid-word.

**Comment by rachelmcr** [comment]
This was found again in alpha testing by Mo, Moto X 2, Android 6.0:

> Related, once you switch something to bold (Selct word and tap B), toggling it off and typing reverts back to bold unless you type a space first and then start typing again.
> 1. type a word
> 2. select it
> 3. tap B to bold it
> 4. tap B again to disable bold
> 5. type another letter
> 
> That letter will be bold but probably shouldn’t.

It's also a problem if you try to remove styles at the end of a word, but before typing a space. As tested on my Nexus 9, Android 6.0.1:
1. Tap B
2. Type a word
3. Tap B (at the end of the word, before the space) -> the B button is no longer highlighted
4. Type a space -> the B button is highlighted again
5. Continue typing and the next word is bold

**Comment by rachelmcr** [comment]
This came up again with a user trying out the latest 5.4 release. Her steps:
1. Tap the italics format button
2. Type a word
3. Tap the italics format button again
4. Type a space and another word

She was surprised that the second word was still in italics. She expected to be able to disable italics immediately after the end of the first word. Her reasoning for disabling italics before typing a space: If she types a space and then disables italics, then if she goes back to add text there later it will end up italicized when she doesn't want it to be.

She also noted that there wasn't enough color contrast between the enabled and disabled format buttons for her to see that the italics formatting was still enabled.

**Comment by aforcier** [comment]
'Fixed' in #427 by changing the editor's behavior when applying formatting inside a word to apply the formatting to the entire word.
