### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jgorset** [wordpress-mobile/WordPress-Editor-Android#125]
Hi guys, and thanks for sharing this!

We're pretty big on open source and we'd love to use and contribute to it, but while we open source most of the things that go into our commercial applications we can't license the application itself under GPLv2. 

I'm sure you had good reasons to change your license from MIT to GPLv2 in 9645409a8e64d03998057072d6109ca27eb76f9b and indeed I think it makes sense for a platform such as WordPress proper, but I just wanted to make sure that you've considered the implications of licensing libraries such as this one under the same license. We open source everything under MIT because it allows more people to use and contribute to it, which we think pushes open source forward.

:cake:

**Comment by bummytime** [comment]
Thanks for the feedback @jgorset.    

> I'm sure you had good reasons to change your license from MIT to GPLv2 in 9645409 and indeed I think it makes sense for a platform such as WordPress proper, but I just wanted to make sure that you've considered the implications of licensing libraries such as this one under the same license. 

We did indeed...WordPress is and always has been GPL licensed.

**Comment by jgorset** [comment]
Alright, cool, I can totally appreciate that.
