### ISSUE TITLE
Edit Images

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#13]
Tapping an image loads the image settings screen, which we might want to change to mirror the options offered in the iOS version. Here are the current screens on Android and iOS:

![01-image_properties_comparison](https://cloud.githubusercontent.com/assets/9613966/6908073/f5a7e6e2-d708-11e4-95f1-ab7ab6485427.png)

We might also want to change the tap interaction itself. Currently in Android, tapping an image while in edit mode will launch the 'Image settings' screen right away. By contrast, the iOS editor requires two taps. The first blurs the image and overlays an 'Edit' message:

![02-ios_edit_image](https://cloud.githubusercontent.com/assets/9613966/6908076/f98ea1ba-d708-11e4-98a0-5b880e52ce97.png)

Tapping again will display the 'Edit image' screen for iOS shown above.

**Comment by bummytime** [comment]
Just as a FYI, this is the current image edit overlay:

![screen shot 2015-03-30 at 6 41 02 pm](https://cloud.githubusercontent.com/assets/154014/6909523/a5c117ee-d70c-11e4-8a35-d22b9a5d6e38.png)

> We might also want to change the tap interaction itself. Currently in Android, tapping an image while in edit mode will launch the 'Image settings' screen right away. By contrast, the iOS editor requires two taps. 

I am not really sure about the genesis of the two tap gesture on iOS. Perhaps @thianhlu knows?

Also Ref: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/549 and https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/427

**Comment by aforcier** [comment]
I'm re-working the image setting screen and need some input. Here's the current version (needs some polish like aligning the captions with the EditTexts):

![13-image-settings-sample](https://cloud.githubusercontent.com/assets/9613966/9600950/f9e3e75c-50a6-11e5-9f20-eedae362cea6.png)

A couple of points:
- I added the missing options from iOS (alt text and link)
- I dropped the selection bar for width, replacing it with a spinner with the options iOS has (Full Size, Thumbnail, Medium and Large)
- Especially with the alt text field now added, I think that labels are necessary for the 3 text fields at the top. If they're all filled out, there are no hints, and it's not at all clear which is the title, the caption and the alt text. I used the existing labels to demo it out.
- On a smaller screen (or in landscape mode), 'Image Settings' and the buttons at the bottom stay static, and the rest of the screen scrolls:

![13-image-settings-sample-landscape](https://cloud.githubusercontent.com/assets/9613966/9601105/1bb1d80c-50a8-11e5-978e-033422190a31.png)

None of this is hooked up to WPAndroid yet, and featured image support might not make it as part of the upcoming first media integration with WPAndroid, but I included the checkboxes WPAndroid legacy uses to show the complete image settings screen.

What do you think @thianhlu?

**Comment by thianhlu** [comment]
@aforcier Great start. A few things we will want to try:

1) Align all titles, labels and inputs to the left. 24dp padding on the left and right.
2) Spacing between text field inputs is too tight. Lets follow material design guideslines on this one. https://cloudup.com/clozrrLtlFS
3) Same goes for scrolling within dialog. Lets add some separators so there is a better separation between main label and content. https://cloudup.com/igNxQ4ZG_Pb

**Comment by aforcier** [comment]
About image resizing - the iOS editor offers a list of predefined sizes (Thumbnail, Medium, Large and Full), with the size for each category obtained from the user's blog:

![ios_image_properties](https://cloud.githubusercontent.com/assets/9613966/9720528/938b4662-5597-11e5-8298-d9187ccb3304.jpg)

Those values are taken from the user's WP settings:

<img width="482" alt="wp-media-settings-image-sizes" src="https://cloud.githubusercontent.com/assets/9613966/9720545/acde3e58-5597-11e5-98ba-97d98d1c4c59.png">

Right now WPAndroid doesn't support predefined image sizes. This isn't an XML-RPC issue - the API supports retrieving the max width/height settings for each image size predef, we just don't retrieve or store that information currently. We have an open issue for this, which was ported over from WPAndroid: #112.

What WPAndroid does instead is allow the user to set a maximum width for image uploads from an Android device:

![13-wpandroid-media-settings](https://cloud.githubusercontent.com/assets/9613966/9720554/bed564a6-5597-11e5-9fb8-2b94a9e8521b.png)

Then, when editing an image inside a post, there's a slider which lets the user resize the image (up to the image's natural width or the max width set in the settings above, whichever is lower):

![android_image_properties](https://cloud.githubusercontent.com/assets/9613966/9720504/6cade7ca-5597-11e5-8e7a-cb0d9d6a9924.png)

To simplify the (already huge) PR integrating media in the new editor with WPAndroid, I'm thinking of dropping support for predefined sizes from the media settings for now, and keeping the slider. #112 will stay open and we'll implement it separately. Here's what the new image option screen looks like currently:

![13-edit-images-width-slider](https://cloud.githubusercontent.com/assets/9613966/9720563/d2f89250-5597-11e5-8bc3-e08b9ac4bb39.png)

@thianhlu: What do you think? We can left-align that slider, but it ends up cutting off part of the slide animation (and even part of the indicator dot itself, depending how far we align it):

https://cloudup.com/cU2gOa3B7mi

(the screenshot above uses the default Android SeekBar with no padding changes)

cc @bummytime, @thianhlu, @meremagee

**Comment by thianhlu** [comment]
@aforcier Can we make the slider full width?

**Comment by bummytime** [comment]
@aforcier I am definitely in favor of dropping predefined sizes from this PR. Slider works for me.
