### ISSUE TITLE
Small viewport on landscape devices

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#130]
With the addition of the format bar, some phones have a very small viewport with the keyboard up:

![landscape-nexus4-narrow-viewport](https://cloud.githubusercontent.com/assets/9613966/7204940/ebc19d6e-e4f3-11e4-9ee8-3c9019920b9c.png)

(Nexus4, landscape mode, standard keyboard, API 22)

One idea might be to use fullscreen mode while editing if the viewport is below a certain size. This would be tied to scrolling: fullscreen mode while scrolling down and editing, exit fullscreen and restore the action bar when scrolling up. See the Pocket app for an example.

**Comment by bummytime** [comment]
Ping @thianhlu...this is really too small. I think going full screen is prolly something we must do. Also, here is landscape on a Nexus 9 tablet:

![screen shot 2015-04-30 at 9 42 25 am](https://cloud.githubusercontent.com/assets/154014/7415348/da7ddd04-ef1d-11e4-9684-962177f8c78a.png)

Even this feels a little cramped. For reference, here is the current editor when the content body has focus (Action bar is hidden):

![scaled shamulmy47mbummytime04302015095234](https://cloud.githubusercontent.com/assets/154014/7415482/d1ce0df4-ef1e-11e4-93f5-0c1121cfd588.png)
