### ISSUE TITLE
Animate format bar selection

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#131]
Example: https://cloudup.com/cb2NTJ_8DxQ

**Comment by thianhlu** [comment]
related to #145

**Comment by bummytime** [comment]
iOS Animation implementation was here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/678

**Comment by aforcier** [comment]
First pass:

https://cloudup.com/cpuLSkcC5py

What do you think @bummytime @thianhlu?

**Comment by thianhlu** [comment]
:+1:  you can also remove underline at this point as well
