### ISSUE TITLE
Graphical affordance needed for format bar scroll

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#134]
As mentioned in #133, we should add some kind of graphical affordance that let's the user know then can scroll the format bar on smaller screens. Currently:

![screen shot 2015-04-24 at 10 48 26 am](https://cloud.githubusercontent.com/assets/154014/7323400/d9e9e77e-ea73-11e4-885a-ab1b14573b74.png)

**Comment by thianhlu** [comment]
something like this? wip

![](https://cloudup.com/c_SfVj-ns_b+)

**Comment by bummytime** [comment]
@thianhlu I think you are on the right track here. Should the user see this in landscape?

**Comment by thianhlu** [comment]
They shouldn't see the drop-shadow is nothing is flowing underneath.  Lemme keep working on this one.

**Comment by bummytime** [comment]
This has been addressed in #149
