### ISSUE TITLE
Formatbar updates

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-Android#145]
- [x] Disabled button state
- [x] Default button state
- [x] Active button state (remove underline)
- [x] Tap animation on default button
- [x] Spacing toolbar mobile 
- [x] Spacing toolbar tablet
- [x] Horizontal scroll for smaller viewports
- [ ] Onboarding for horizontal scroll users (use same tip as iOS, https://cloudup.com/cXNZSt6Ek32)

**Comment by bummytime** [comment]
This looks great @thianhlu!

**Comment by aforcier** [comment]
:+1: we'll be better-looking on Android than on iOS! (briefly)

**Comment by thianhlu** [comment]
@aforcier new icons 
https://cloudup.com/cu1cPa1nJZ4

**Comment by aforcier** [comment]
Looking good @thianhlu!

**Comment by thianhlu** [comment]
Adding in a few new notes here:

- [ ] Remove 5pt padding on format bar icons on small & normal phone layout. Leave for Tablet layout
- [ ] Remove chevron on normal phone layout (also remove horizontal scroll and tip). Leave this all in place for small phone layout. We will default to regular divider shown here:

![](https://cloudup.com/i7Qs2FNstB1+)

**Comment by bummytime** [comment]
We'll leave onboarding open in #7
