### ISSUE TITLE
New editor tracking

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#15]
The new editor should be wired up to mixpanel just like iOS.

**Comment by maxme** [comment]
Don't forget to update Nosara Tracks event names - Ref. the recently merged PR: https://github.com/wordpress-mobile/WordPress-Android/pull/2468

**Comment by aforcier** [comment]
Possible addition (otherwise we can cut a separate issue): add tracking for the user adding a featured image, distinguishing between the post settings and the image settings screen.

(Ref: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/16#issuecomment-157534189)

**Comment by maxme** [comment]
I took editor event names from WP-iOS and compared with legacy event names:

<img width="920" alt="screen shot 2016-01-04 at 15 21 20" src="https://cloud.githubusercontent.com/assets/40213/12091385/0a273648-b2f7-11e5-9cd1-8a2d47c25df2.png">

That gives us the following list:

```
EDITOR_ADDED_PHOTO_VIA_LOCAL_LIBRARY,
+ EDITOR_ADDED_VIDEO_VIA_LOCAL_LIBRARY,
EDITOR_ADDED_PHOTO_VIA_WP_MEDIA_LIBRARY,
+ EDITOR_ADDED_VIDEO_VIA_WP_MEDIA_LIBRARY,
+ EDITOR_CLOSED,
? EDITOR_CLOSED_POST,
EDITOR_CREATED_POST,
+ EDITOR_DISCARDED_CHANGES,
+ EDITOR_EDITED_IMAGE,
+ EDITOR_ENABLED_NEW_VERSION,
EDITOR_PUBLISHED_POST,
EDITOR_SAVED_DRAFT,
EDITOR_SCHEDULED_POST,
+ EDITOR_TOGGLED_OFF,
+ EDITOR_TOGGLED_ON,
EDITOR_UPDATED_POST,
+ EDITOR_UPDLOAD_MEDIA_FAILED
+ EDITOR_UPDLOAD_MEDIA_RETRIED
- EDITOR_PUBLISHED_POST_WITH_PHOTO,
- EDITOR_PUBLISHED_POST_WITH_VIDEO,
- EDITOR_PUBLISHED_POST_WITH_CATEGORIES,
- EDITOR_PUBLISHED_POST_WITH_TAGS,
EDITOR_TAPPED_BLOCKQUOTE,
EDITOR_TAPPED_BOLD,
+ EDITOR_TAPPED_HTML,
EDITOR_TAPPED_IMAGE,
EDITOR_TAPPED_ITALIC,
EDITOR_TAPPED_LINK,
EDITOR_TAPPED_MORE,
+ EDITOR_TAPPED_ORDERED_LIST,
EDITOR_TAPPED_STRIKETHROUGH,
EDITOR_TAPPED_UNDERLINE,
+ EDITOR_TAPPED_UNLINK,
+ EDITOR_TAPPED_UNORDERED_LIST,
```

I'll add the new events to https://github.com/wordpress-mobile/WordPress-Analytics-Android - I think `EDITOR_PUBLISHED_POST_WITH*` events must be converted to event properties in `EDITOR_PUBLISHED_POST` (maybe in `EDITOR_SCHEDULED_POST`, `EDITOR_SAVED_DRAFT` and `EDITOR_UPDATED_POST` too)

**Comment by maxme** [comment]
Previous diff made on the wrong analytics version :crying_cat_face:
