### ISSUE TITLE
Formatbar spacing on mobile

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-Android#151]
##### BIG - Equal or greater than width of 375pt (\* 375pt width below)

![](https://cloudup.com/cYL4zzTjKui+)

---
##### MEDIUM - Less than 375pt width & equal to and greater than 320pt (\* 320pt width below)

![](https://cloudup.com/cRj5JR60cKb+)

---
##### SMALL - Less than width of 320pt

![](https://cloudup.com/cDUoYWMGW0H+)
- Implement chevron overflow for horizontal scroll
- Keep same spacing as Medium sizing
- box-shadow: -1px 0 2px 0 rgba(#2E4453, 0.5)

**Comment by thianhlu** [comment]
related to #145

**Comment by bummytime** [comment]
Note that [like on iOS](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/663), the format bar button height was increased.

So icon sizes are now currently: 
- mdpi = 44 (baseline)
- hdpi = 66
- xhdpi = 88
- xxhdpi = 132

**Comment by thianhlu** [comment]
@bummytime I think this is all of them (default, highlighted, disabled) for all those sizes

https://cloudup.com/cIDyu1ULJtP

**Comment by bummytime** [comment]
Thanks @thianhlu!

**Comment by thianhlu** [comment]
@thianhlu need chevron as well in those 4 sizes

**Comment by thianhlu** [comment]
@bummytime 
https://cloudup.com/cIpIR8utJVy

I am using material design chevron since is really similar to iOS but slightly thicker
