### ISSUE TITLE
Webview does not scroll if caret is below soft keyboard (API 14 + 15)

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#155]
Title has it, Video of the bug in action: https://cloudup.com/cLyb5hEdg70

Ref: #154

**Comment by bummytime** [comment]
FYI, this affects about 7% of our users as of June 2015.

**Comment by aforcier** [comment]
Closing, minSdk is now `16`: https://github.com/wordpress-mobile/WordPress-Android/pull/4123.
