### ISSUE TITLE
Glitchy switching between fields on API 19+

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#158]
Due to autocorrect on API 19+, switching between fields doesn't work properly when in the middle of typing a word.

For example, if typing a word in the title field, touching the content field will not move the cursor to the content field. The only way to change fields is to double-tap or to long-press. This bug does not occur right after a space or newline (i.e., when there are no suggestions displayed).
- Confirmed that the problem persists even after removing the `ZSSEditor` entirely and just loading an HTML file with two `contenteditable`s

**Comment by bummytime** [comment]
Tested: Does **not** fail on Samsung S6 (API 21)

**Comment by aforcier** [comment]
This issue seems to have been caused by a bug in the Android System WebView, which has been fixed.

The bug was introduced in Chromium `v42` (first stable release `42.0.2311.68`) and appears to be fixed as of `v43` (first stable release `43.0.2357.65`).

I can also confirm that the issue wasn't present from the factory version shipped with Android L (`v39`) until `v42`. This should mean that it also doesn't affect devices running KitKat, which is locked on Chromium `v33` as of KitKat version `4.4.3`. I couldn't get hold of a physical `API19` device to test, but I can't reproduce the bug on an `API19` emulator, which should be running the correct Chromium version internally.

**Comment by aforcier** [comment]
Given the above, I'm closing the issue, as it should only occur on `API 21+`, and is resolvable by updating the `WebView`.

**If this issue is reported by a user, it might mean that their System `WebView` is out of date (`v42`) and they should update it**
