### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#16]
Handle setting, modifying and removing the featured image.

Setting the featured image is currently part of `Image Settings` on Android, while on iOS it's contained in `Post Settings`.

Related issues:
[WordPress-Editor-Android#13](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/13)
[WordPress-Editor-Android#6](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/6)
https://github.com/wordpress-mobile/WordPress-Android/issues/169

**Comment by aforcier** [comment]
Relevant (adds a reference to the featured image's id to the `posts` table of WPAndroid): https://github.com/wordpress-mobile/WordPress-Android/pull/2916

**Comment by aforcier** [comment]
Ideally, we can allow each individual image to be set as featured through its own image settings, but also allow the featured image to be set/changed through `Post Settings` as on iOS.

**Comment by aforcier** [comment]
This one's nearly ready for a PR, but I'd like some input before I open it.

First, here's the current featured image flow with the legacy Android editor:

https://cloudup.com/c4olwoeZVzU

The featured image is set by tapping on an image in the post and checking a box (only possible for local drafts on legacy).

This is different from iOS, where the featured image is set in the post settings instead:

https://cloudup.com/cM-r3kN-ofN

This is more similar to the web than the Android legacy implementation is, where you set the featured image from the sidebar:

![16-featured-image-web](https://cloud.githubusercontent.com/assets/9613966/11022688/d7e2e312-8632-11e5-8a15-7ae7bf4c07b6.png)

For our new editor, I'm trying out implementing both methods (image-specific settings and post settings). I personally prefer the image-specific setting flow (as on Android legacy) on mobile, and in any case it's probably good to keep functionality that users are used to from legacy where possible.

<h3>Setting the featured image from image settings</h3>

Here's the flow for changing the featured image through image-specific settings (PR forthcoming):

https://cloudup.com/caRCGPOBaxV

One change from legacy is that I dropped the second checkbox: 'Include image in post content'. In the legacy editor, if you leave that checkbox unchecked, the image stays in the draft, but upon uploading the post the featured image would be set and the image stripped from the contents of the post.

For the new editor I think we can drop that checkbox, for two reasons:
1. In the new editor the image has already been uploaded before it can be set as featured, and the post data is updated with the id for the featured image. So unlike legacy, it's possible to set an image as featured, delete it from the post content, and still keep it as the featured image for the post.
2. Assuming we're including the option to set the featured image from the post settings, that's a way of setting the featured image without having to add it to the post contents first.

<h3>Setting the featured image from post/page settings</h3>

Here's how the post/page settings screen looks with the featured image added:

![16-featured-image-post-settings](https://cloud.githubusercontent.com/assets/9613966/11022708/459ba4b6-8633-11e5-914c-44e73edf5492.png)

For now, there are only two things you can do (with the featured image) on this screen:
1. Select an image from the user's WP media library (either to set the featured image for the first time or to change the existing featured image)
2. Removing the existing featured image if set

Here's a flow demo that also shows the context menu with these two options:

https://cloudup.com/c48DR5tIcAT

Implementing the full range of options we normally have for adding media to the editor (upload media from the device's storage, take photo/video) should be a separate issue, as this is already becoming a hefty set of changes.

(The WP media gallery option which I did include is the easiest to implement since nothing is being uploaded and no progress updates are needed.)

My suggestion is to keep the featured image option in the post settings with just those two options for the internal beta. That way we can still get feedback on the flow.

Alternatively, we can put the featured image option in the post settings screen on hold for later (when we've added in the missing media options) and only include the image-settings method of setting the featured image in the 0.5 milestone.

Thoughts and design/UX feedback @bummytime @thianhlu @meremagee?

**Comment by bummytime** [comment]
Nice work so far here @aforcier!

There is a balance between what the Android users are expecting and maintaining (a little?) parity with the web. In my head, I would expect to set the featured image in post options....but I am not our users either. :-) 

> Implementing the full range of options we normally have for adding media to the editor (upload media from the device's storage, take photo/video) should be a separate issue, as this is already becoming a hefty set of changes.

I agree totally.

> My suggestion is to keep the featured image option in the post settings with just those two options for the internal beta. That way we can still get feedback on the flow.

Maybe because it's Monday morning and I need more coffee, but are you suggesting we keep both flows for the internal beta?

**Comment by aforcier** [comment]
> are you suggesting we keep both flows for the internal beta?

Yes, I'm suggesting keeping both the image settings flow and the post settings flow (though the latter only with the two options I mentioned for now: add from WP media library and remove existing featured image).

**Comment by bummytime** [comment]
Roger. I can get behind that.

**Comment by thianhlu** [comment]
So overall looks really good. Thanks for supporting the legacy stuff for now. We may want to track which flow ends up using both and deprecating over time. Since things are going more the way of Calypso, we will probably go more of the Post Settings route. 

On the image post view, the margins are too tight. Can we match them to your Image Settings page.
https://cloudup.com/c6aa1o0VMnp
Also the spacing for text inputs should match your Image Settings page as well.

**Comment by meremagee** [comment]
> Yes, I'm suggesting keeping both the image settings flow and the post settings flow (though the latter only with the two options I mentioned for now

How will we know when to deprecate one flow or the other? Will we be basing the decision on qualitative beta tester feedback, making sure the flows make sense? How much friction would it add to release to get some tracking on like, add_featured_via_image_settings vs add_featured_via_post_settings (not sure what event taxonomy/naming conventions are)? I like your thought process on supporting legacy flows while introducing more standard wp flows, but I'd like to keep an eye on streamlining in an informed way down the road.

> In the new editor the image has already been uploaded before it can be set as featured, and the post data is updated with the id for the featured image. So unlike legacy, it's possible to set an image as featured, delete it from the post content, and still keep it as the featured image for the post.

This is handy, but I think it warrants an alert if the image is set to featured and then deleted in post content, something like, "this image is still set as the featured image for the post/page. you can manage in post settings...". Though this makes sense from a wp perspective, it's a rather complex technical detail that I don't want to assume users, especially new users, will understand. I'll add a new issue for the alert - not a blocker for this iteration.

> Implementing the full range of options we normally have for adding media to the editor (upload media from the device's storage, take photo/video) should be a separate issue, as this is already becoming a hefty set of changes.

Sounds good. The difference between local and remote media libraries are less obvious on mobile than on web, so I'll be curious to see if this is tricky or complex. If we see feedback in the beta that it's weird, we can course correct and see what needs to be ready for release.

**Comment by meremagee** [comment]
> One change from legacy is that I dropped the second checkbox:

I'm seeing the 2nd checkbox - do I have an outdated build? https://cloudup.com/iBSy-XyoETa. I do see that it's removed in legacy editor, so I'm guessing merges are just out of sync?

**Comment by aforcier** [comment]
> How will we know when to deprecate one flow or the other? Will we be basing the decision on qualitative beta tester feedback, making sure the flows make sense? How much friction would it add to release to get some tracking on like, add_featured_via_image_settings vs add_featured_via_post_settings (not sure what event taxonomy/naming conventions are)?

I think beta tester feedback is the main way to go for the first iteration, as we add tracking for this and collect data. I added a note about this to the editor-wide tracking issue (#15, part of the current milestone). It should be doable to distinguish between the two (post settings vs image settings). Would we want to track the setting of a featured image as soon as it happens or upon uploading the post? The former would add the least friction in terms of implementation. It might also be the more meaningful statistic for what we're trying to do, since a user could be using both flows but in different ways. If we only capture on upload, we're throwing away earlier changes to the featured image.

> I think it warrants an alert if the image is set to featured and then deleted in post content, something like, "this image is still set as the featured image for the post/page. you can manage in post settings...".

:+1:

> The difference between local and remote media libraries are less obvious on mobile than on web, so I'll be curious to see if this is tricky or complex. If we see feedback in the beta that it's weird, we can course correct and see what needs to be ready for release.

:+1:

> I'm seeing the 2nd checkbox - do I have an outdated build? https://cloudup.com/iBSy-XyoETa. I do see that it's removed in legacy editor, so I'm guessing merges are just out of sync?

My demos above aren't live yet, they're from an unmerged branch (your build is fine). Once I add @thianhlu's changes I'm ready to open a PR for this, since we agreed to postpone local media support for the post settings screen.

Re: legacy editor, the checkbox is normally hidden - it only appears once you check 'Use as featured image'. I'll be leaving that in place (on legacy) since we're avoiding any changes to the legacy editor (and its use makes more sense for legacy since there's no other way to add a featured image without including it in the content).
