### ISSUE TITLE
Confusing new post experience

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Editor-Android#164]
When I start a post, I'm taking to what appears to be a blank screen with a bottom formatting bar. The keyboard isn't showing, and there's no hint in either field that tells me what I'm supposed to type. I think there needs to be a hint in the title field, and the keyboard should automatically appear.

![blank-editor](https://cloud.githubusercontent.com/assets/3903757/8187080/fc032a92-141b-11e5-938f-e6930d0508cd.png)

**Comment by aforcier** [comment]
Related to https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/120

**Comment by aforcier** [comment]
Resolved in #189. The keyboard not being displayed on load issue is tracked in #120.
