### ISSUE TITLE
EditorFragment shouldn't hold a reference to its containing activity

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Editor-Android#166]
`EditorFragment` uses `mActivity` to hold a reference to the containing activity, which isn't necessary since you can use the fragment's `getActivity()` instead. More importantly, holding a reference to the activity risks leaking that activity given the (awful) nature of the fragment lifecycle.

In a nutshell, when you rotate the device, or the device is running low on memory, the fragment's activity may be re-created. This can cause the activity to be leaked if you hold a pointer to it like `mActivity` since otherwise the garbage collector would free it.

Related to the above, there's no guarantee that the fragment is attached to an activity, so anytime the activity is accessed there should first be an `isAdded()` check. It sounds bizarre, but if you peruse the WP Android repo you'll find countless issues where the app crashed with an NPE because we failed to call `isAdded()` before accessing the activity.

Last but not least, it looks like a big reason you have `mActivity` is so you can access its ActionBar. I recommend not using `mActionBar` here for the same reasons I outlined above. Instead, using a routine like this everywhere you want to access the ActionBar would be more error-resistant:

```
private ActionBar getActionBar() {
    if (!isAdded() return null;
    if (getActivity() instanceof AppCompatActivity) {
        return ((AppCompatActivity)context).getSupportActionBar();
    }
    return null;
}
```

Feel free to ping me if you have any questions.

**Comment by bummytime** [comment]
Fixed in #167
