### ISSUE TITLE
Inserts two '\n' on enter/return key pressed

### ISSUE THREAD

**Issue by dkadrikj** [wordpress-mobile/WordPress-Editor-Android#174]
When hitting enter/return key it inserts two '\n'. Also, if you try to hit once more on enter/return it replaces both '\n' with a single one.

Example, this text:

Hi,
How are you?

New paragraph.

is represented as:

Hi,\n\nHow are you\nNew paragraph

**Comment by aforcier** [comment]
Looks like an old editor issue that we'll get rid of in the transition to the new editor.

**Comment by rachelmcr** [comment]
I can't reproduce this behavior in the new editor (version alpha-4). I'm going to go ahead and close this since it's resolved in the new editor.
