### ISSUE TITLE
Format bar (tablet) 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#18]
On the iOS editor, the iPad format bar buttons were updated to the following:

![screen shot 2015-03-30 at 11 10 05 am](https://cloud.githubusercontent.com/assets/154014/6900623/6c66eb70-d6cd-11e4-9017-587860d5a37f.png)

This was a completely data-driven decision based on usage metrics. Not sure if Android users will have different needs, but we should find out. Also note how the layouts differ between tablet and phone.

For context, the current editor has the following:

![screen](https://cloud.githubusercontent.com/assets/154014/6900657/93d8a504-d6cd-11e4-9a5f-6eb04927a995.png)

/cc @thinahlu @meremagee

**Comment by aforcier** [comment]
Some notes:
- Mimic the spacing and grouping.
- Aiming for no scrolling on tablet - fallback to phone bar if the display isn't wide enough.

**Comment by aforcier** [comment]
Should we only show the tablet-sized format bar on devices that are always able to show it, regardless of orientation? For example, some phones can fit the tablet bar on landscape, but not on portrait.

This seems to be the treatment on the iOS editor: the iPhone 6+ still shows the phone-sized tablet bar on landscape, even though the tablet-sized one would fit.

What do you think @bummytime, @thianhlu, stay consistent?

**Comment by thianhlu** [comment]
Yeah prob consistent.

**Comment by bummytime** [comment]
@aforcier Yeah I agree with @thianhlu. We should probably define what "tablet" actually means (e.g. `res/layout-sw600dp`)...

**Comment by aforcier** [comment]
@bummytime `sw600dp` is what I'm using for now, here's what the format bar looks like atm on a 600dp-wide screen (NVIDIA shield):

![format-bar-tablet-600dp-portrait](https://cloud.githubusercontent.com/assets/9613966/7377992/396960e8-edb8-11e4-8682-0fd800ba14b4.png)

**Comment by bummytime** [comment]
Lookin' good!

![giphy](https://cloud.githubusercontent.com/assets/154014/7378197/4c9e28ee-edb1-11e4-8a23-74396c5e3529.gif)
