### ISSUE TITLE
Insert a link via visual editor

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#185]
When the user taps the link icon, show an insert link modal. We probably can re-use the existing logic in the existing Android editor:

![2015-07-16 12 20 39](https://cloud.githubusercontent.com/assets/154014/8730354/ce9a42f0-2bb5-11e5-9d90-2679fd80a9dd.png)

/cc @thianhlu

**Comment by thianhlu** [comment]
Yeah re-use sounds good.
