### ISSUE TITLE
Action bar hides unexpectedly in landscape

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#196]
As reported in #195 — Noticed one remaining ActionBar glitch that wasn't described in the original issue:
1. start in portrait and dismiss the soft keyboard
2. rotate to landscape
3. The keyboard stays hidden, but the ActionBar is also hidden. Bringing up the keyboard will keep the ActionBar hidden, and hiding the keyboard again will correctly show the ActionBar.

Tested this on my S6 and it worked as expected (keyboard stayed up in landscape with action bar hidden)...every other API/device was :-1:

**Comment by bummytime** [comment]
This also happens if already in landscape mode when the editor is launched.

**Comment by aforcier** [comment]
Bonus: this also happens on an API 18 Samsung S3, even if the software keyboard is disabled and a hardware keyboard is connected (every other tested device never dismisses the ActionBar if the software keyboard is disabled).
