### ISSUE TITLE
New post workflow (WIP)

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#2]
Using the new visual editor on iOS as inspiration:

![screen shot 2015-03-25 at 10 32 44 am](https://cloud.githubusercontent.com/assets/154014/6829061/24b44972-d2df-11e4-8101-563023b44d43.png)

 the Android editor will be updated to reflect the new visual look & feel as well as have 100% visual editing for new _and_ existing posts. For context, here are the existing editor screens on Android:

<h4>New Post: </h4>

![new_post_1](https://cloud.githubusercontent.com/assets/154014/6829613/888eb074-d2e2-11e4-858d-d743e23931a2.png)

<h4>New Post Title:</h4>

![new_post_title](https://cloud.githubusercontent.com/assets/154014/6829678/feb2e248-d2e2-11e4-9113-a4905fe54238.png)

<h4>New Post Content:</h4>

![new_post_content](https://cloud.githubusercontent.com/assets/154014/6829688/1278fbfa-d2e3-11e4-8d7b-b31c95fa76aa.png)

@thianhlu We'll need you to provide some input here. :grinning:

**Comment by bummytime** [comment]
[Here's a video](https://cloudup.com/cCNCgX9Hme2) of the existing new/edit post workflow for posterity's sake.

**Comment by aforcier** [comment]
Closing - the new Android editor now closely matches the iOS editor's new post workflow:
- Placeholders in empty fields
- Text styling, side margins
- Post settings button in ActionBar rather than bottom button
- No more full-screen content editing mode
