### ISSUE TITLE
Redesign bottom toolbar in "preview" mode

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#20]
In the current Android editor when you select an existing post, it opens in a preview mode and displays a bottom toolbar that contains a few actions related to the post:

![screen shot 2015-04-02 at 9 55 17 am](https://cloud.githubusercontent.com/assets/154014/6966487/076ede90-d91f-11e4-985a-8d842d22f3a2.png)

(Delete, Preview, Share, Add a comment, Edit)

I am assuming we will refactor this in some way.

/cc @thianhlu

**Comment by aforcier** [comment]
Related: #223

**Comment by aforcier** [comment]
The bottom toolbar was dropped from the editor preview in this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/2963

Closing this issue, keeping #223 as the main issue tracking Preview changes.
