### ISSUE TITLE
Editor stripping <p> tags

### ISSUE THREAD

**Issue by alexcrist** [wordpress-mobile/WordPress-Editor-Android#202]
It seems that when I set the content of the EditorFragment to any text containing <p> tags, they are stripped.

e.g.: 

```
String input = "<p>this is an example</p>"
mEditorFragment.setContent(input);
mEditorFragment.getContent(); // >> "this is an example"
```

**Comment by aforcier** [comment]
The editor strips `p` tags (other tags are left alone) for parity with the web version of the WordPress editor.

This is handled by [wpload.js](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/e7ca66a6b1619a9b485bb976dd32e6a77bb1e1cd/libs/editor-common/assets/wpload.js) and [wpsave.js](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/e7ca66a6b1619a9b485bb976dd32e6a77bb1e1cd/libs/editor-common/assets/wpsave.js) from within the `ZSSRichTextEditor`.

**Comment by alexcrist** [comment]
Aha thanks!
