### ISSUE TITLE
Blockquote after list wraps list in quote

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-Android#210]
Adding a blockquote after lists wraps lists in quote as well.

device: SM-T330NU (samsung)
Android version: 4.4.2

repro:
- add a list (ol or ul)
- exit list
- type regular p text
- tap `blockquote` to quote p text
- note that previous list items are also wrapped in blockquote

video: https://cloudup.com/cOgZJgJQfDO

![](https://cloudup.com/iCSjF6Njv-X+)

_possibly related, though I cannot repro https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/161_

**Comment by bummytime** [comment]
While in the visual editor if you tap the list format bar button (when you are all done with your list) the editor does not create a new paragraph. Instead it puts the new text directly under the existing list: 

![screen shot 2015-08-12 at 7 09 37 pm](https://cloud.githubusercontent.com/assets/154014/9239905/0e41164c-4126-11e5-93dc-99cc66113d42.png)
When the blockquote button is pressed, it surrounds the parent node of the node where the cursor is with a `<blockquote>` tag:

![screen shot 2015-08-12 at 7 20 22 pm](https://cloud.githubusercontent.com/assets/154014/9239999/43d2d524-4127-11e5-8805-801f63b1ef4f.png)
This is "technically" the correct behavior of our blockquote logic. The question is when a list is ended, do we automagically create a new `<p>`? When this is done, the blockquote logic works as expected. 

It is interesting to note that if you take the post content above (in the 1st image) and pop into HTML mode and then back again, our load/unload scripts actually "fix" the HTML:

![screen shot 2015-08-12 at 7 10 07 pm](https://cloud.githubusercontent.com/assets/154014/9240162/b7242c70-4128-11e5-9517-b383df88d8d9.png)

/cc @meremagee

**Comment by bummytime** [comment]
Also, wp-admin seems to do this:

![screen shot 2015-08-12 at 9 15 44 pm](https://cloud.githubusercontent.com/assets/154014/9241299/5ca5d30c-4137-11e5-931a-f744a7121f8a.png)
