### ISSUE TITLE
HTML mode can crash on API 16

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#218]
In API 16 versions `4.1` and `4.1.1` only (fixed in `4.1.2`), switching to HTML mode can cause the app to crash. This is due to an Android bug - the crash is triggered by having spanned text that is being line-wrapped. Here is the AOSP issue:

https://code.google.com/p/android/issues/detail?id=35466

This happens consistently with the example app on a Nexus 4 emulator running `4.1.1`. In actual use of the editor, the crash would depend on the device size and the HTML contained in the post being edited. If any one piece of formatted text has to line-wrap, the crash occurs on loading HTML mode.

The simplest fix would be to disable coloring the HTML for those versions (functionally it would all work the same as on other versions, we just wouldn't color the HTML tags).

This would affect under 1% of users (~6% are using `API 16`, but most of those are on the patched `4.1.2` version).

**Comment by aforcier** [comment]
Update: This turns out to have been fixed in `4.1.2`, which was the last version of `API 16` and the version most users on `API 16` are running. Updated the issue.

**Comment by bummytime** [comment]
> The simplest fix would be to disable styling the HTML for those versions.

Given the small percentage of users this seems the most pragmatic. Thinking out loud, I am wondering if we could display a dialog if the user attempted to go into HTML mode: "Sorry, the version of Android you are using is belly up."

/cc @meremagee

**Comment by meremagee** [comment]
<del>That's a great interim solution. Optimum would be if we could maintain the "disabled" state of the HTML button for users with the old os, then also throw the alert ("Sorry, the version of Android...") if the area is tapped. (Longer term would probably make sense to hide the html button entirely on these devices).</del>

<br />
misunderstood the original issue and thought it was that "switching to HTML mode can cause the app to crash." Sounds like we're good to go if we just don't do syntax highlighting and keep all html els styled black.
