### ISSUE TITLE
Format bar: html cut off (Samsung SM-T)

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-Android#219]
In both disabled and active modes, the HTML button is only partially visible on the Samsung SM-T (android 4.4.2) in portrait mode. It fully displays on landscape.

https://cloudup.com/ceNlvS3sufG

**Comment by bummytime** [comment]
@meremagee I think this will be fixed thanks to #220. When we cut a 0.3 build, would you mind checking this again?

**Comment by meremagee** [comment]
still happening in .3 :sob:
