### ISSUE TITLE
Starting post with a list causes issues with blockquote

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#228]
It seems like on APIs < 19, starting the post with anything besides plain text (e.g. a `<ul>` or `<ol>`) causes a number of issues. Most of these issues are hidden from the end user, but can present themselves in different ways. 

The example this issue encapsulates is when a user:
- starts the post with a list
- exits the list by either pressing the list button again or hitting enter twice
- writes some text (a new `<p>`)
- presses blockquote

Nothing will happen. No blockquote. On API's higher than 19, everything works as expected.

Also, it is possible to see a variety of index out of bounds and not defined errors flying around in JS. e.g.:

 `Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1 -- From line 2025 of file:///android_asset/ZSSRichTextEditor.js` 

`Uncaught TypeError: Cannot call method 'toLowerCase' of undefined -- From line 2006 of file:///android_asset/ZSSRichTextEditor.js`

It seems a lot of these errors are rooted in the editor being unable to find the current field (`ZSSEditor.getFocusedField`) or doing node manipulations (`ZSSEditor.closerParentNodeStartingAtNode` and `ZSSEditor.closerParentNode`). 

I tried quite a few cursory attempts to do some null checking and/or provide sensible defaults and the problem just got worse. We may need to think about starting the post differently if anything besides plain text (`<p>` is entered. 

For grins, I did attempt a hack: inserting a `&nbsp;` immediately before a list was inserted and that actually helped matters. This is actually not [unprecedented in the editor either](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/4092508b177db3787898f7faa5d316f7d5608061/libs/editor-common/assets/ZSSRichTextEditor.js#L812-L820). This space is not needed on anything above API > 19. Obviously this is a hack and there may be a better, more fundamental way to handle this issue.

Ref: #226

**Comment by aforcier** [comment]
Can no longer reproduce this bug, on any API level. This was likely fixed by https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/329, or https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/334.
