### ISSUE TITLE
Create post button not visible in some flows

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-Android#231]
samsung galaxy tablet

repro:
- go to my sites
- go to a site detail page
- tap change site
- tap another site to enter site detail page
- note that create post button doesn't appear
- tap blog posts
- create button is displayed
- tap back to go to site detail page
- create button is displayed

![](https://cloudup.com/ifv-JK6OrkZ+)

**Comment by aforcier** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/3030.
