### ISSUE TITLE
Create separate CSS doc to address issues in lower API levels

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#242]
Title has it. Problems with current CSS doc:

<h4>Missing upload progress bar (API < 19)</h4>

On all `API < 19` devices, the progress bar doesn't show up when uploading images. It seems that Android didn't support the `<progress>` tag we're using until the Chromium WebView (`API 19`).  One possibility here is to use an upload notification instead. The WPAndroid app uses those for post uploads and gallery uploads, so we might want to use it for individual image uploads anyway (on all APIs, even ones where the progress bar inside the WebView is shown). Here's a demo of what that would look like on an API 18 device (the notification isn't included in this PR, just looking for feedback):

https://cloudup.com/cqzRAsg_CeE

<h4>Uploading image container is sometimes very small (API < 19)</h4>

Sometimes (probably when uploading media in a blank document, still testing) the image container is very small while uploading. Once the container is removed at the end of the upload, the normal-sized image is shown:

https://cloudup.com/c2HhsInzXsW

The problem is resolved by removing [this](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/244a51315e24eddc0510b422a75e6483c6c0f6f3/libs/editor-common/assets/editor.css#L141) line from the CSS. However, this probably isn't the root cause, and it also breaks the progress bar on `API > 18`.

Ref: #236

**Comment by bummytime** [comment]
In [this](https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/236#issuecomment-135445163) comment we talked about creating a simple overlay like "Uploading..." in lieu of a progress bar for the lower APIs. 

@thianhlu @meremagee @aforcier let's continue the discussion here.

**Comment by aforcier** [comment]
Played with the CSS on older APIs and here's what I have so far:

![242-upload-overlay-text-old-api](https://cloud.githubusercontent.com/assets/9613966/10137628/c15c06e4-65fa-11e5-9bbd-4f4b6e0c9ed1.png)

What do you think @thianhlu @bummytime @meremagee?

**Comment by bummytime** [comment]
@aforcier I like that.

**Comment by thianhlu** [comment]
:+1:

**Comment by tonyr59h** [comment]
Addressed in #270.
