### ISSUE TITLE
Image settings screen navigation fixes

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#261]
Two navigation issues:
1. When tapping the device back button, the app exits the editor instead of just the image settings screen - this is a bug, we should be returning to the editor
2. From conversation with @maxme, we may be risking users pressing X and expecting their changes to be saved in the image settings screen:

![image setttings](https://cldup.com/uI3GXFyyfOu/vPnwmp.png)

Even though the X is unique, in the rest of the app settings changes are persisted when the user hits the back arrow and exits the settings screen, so the user may press the X by habit.

The fix would be to drop the 'SAVE' button entirely and switch the X back to a back arrow, which saves any changes and returns to the editor.

The Android back arrow for reference:

![wpandroid-editor-0 4-screen](https://cloud.githubusercontent.com/assets/9613966/10697648/04c56964-797b-11e5-97fc-aedebf821f10.png)

cc @thianhlu @bummytime @meremagee @maxme

**Comment by bummytime** [comment]
@thianhlu Do you have any thoughts on point #2 above?

**Comment by aforcier** [comment]
Looking at the material design specs, I see what might be a good compromise that we missed in the original implementation.

We can keep the format bar buttons the same (they are following the spec for full-screen dialogs after all), but add a confirmation dialog when the user navigates away (by pressing the X button or the device back button):

![fullscreen-dialog-confirmation](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3Qy04bFg2X0F4UkE/components_dialogs_fullscreen8.png)

(ref: https://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs)

(We'd use something like 'Discard changes to image settings?')

This way we won't be losing changes for users who tap the top left corner out of habit and expect their changes to persist (as we do in other settings screens in WPAndroid).

What do you think? @bummytime @maxme @thianhlu @meremagee

**Comment by thianhlu** [comment]
@aforcier This is a dialog rather a screen right? So to confirm its appearing from bottom? Confirmation dialog is the right route to go. 

Just to confirm, The Save button closes the dialog right? Do we have an subtle UI elements that says "saved" or state change of button before closing dialog?

**Comment by aforcier** [comment]
@thianhlu Yes it's considered a dialog (but a full-screen one). It doesn't appear from the bottom though (the same screen on iOS does slide in from the bottom, maybe that's what you're thinking of?).

The save button closes the dialog but there are no subtle UI elements indicating the save. What about adding a toast saying "Changes saved"? We do the same thing when exiting the editor with changes to the post:

https://cloudup.com/cek8K_---8n

**Comment by thianhlu** [comment]
Cool thanks for confirming. Also, toast would be perfect for this.

**Comment by aforcier** [comment]
To summarize, this issue boils down to:
- [x] Tapping the device back button should return the user to the editor - not exit the editor entirely
- [x] Show a confirmation dialog when the closing the settings dialog with unsaved changes
- [x] Show a toast that changes have been saved when the Save button is pressed

**Comment by aforcier** [comment]
Integrated into WPAndroid in https://github.com/wordpress-mobile/WordPress-Android/pull/3463.
