### ISSUE TITLE
cutsom fields?

### ISSUE THREAD

**Issue by titaniumbones** [wordpress-mobile/WordPress-Editor-Android#263]
It would be extremely useful to me to be able to add custom fields to posts from the mobile app. The particular application is geotagging draft posts that will be composed offline during a Himalayan trek, far away from the Internet.  How hard would it be to add this functionality? Or should I maybe try another method?

**Comment by aforcier** [comment]
We have an open issue tracking custom fields (and taxonomies and post types) [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/114).

The current priority for editing on WPAndroid is a new all-visual editor we're working on, so I can't give a timeframe for when this feature would be added. Hopefully after the new editor is completed we'll be able to make additions like this one - it definitely would be a useful feature.

**Comment by aforcier** [comment]
Closing in favor of #114.
