### ISSUE TITLE
Improve link pasting experience in link dialog

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#268]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/3443

> When I make a bunch of text into a hyperlink in the Android app, the text input field for the link is pre-loaded with `http://` which is actually kind of inconvenient, since almost all links on mobile are copy-pasted from my mobile browser window. Since the field doesn't filter out the double `http://` I have to delete it every time.

The link dialog in the new editor has the same issue as legacy. We should duplicate the iOS app behavior, which auto-fills the URL field with the URL in the clipboard. At the very least, we should filter out double `http://` when pasting in a URL.

**Comment by tonyr59h** [comment]
> We should duplicate the iOS app behavior, which auto-fills the URL field with the URL in the clipboard.

:+1: to that.

After toying around I think it would be nice if the link text field would auto-fill with whatever text your cursor is in the middle of. Currently it will only fill that field if text is highlighted. Thoughts?
