### ISSUE TITLE
Media: Option to upload documents to the media library

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#271]
A user requested the option to upload documents (e.g. PDF files) to the media library in the app.

I found that I can access PDF files on my device, for example, by selecting "Select a photo from gallery" and then choosing Dropbox -> "Show all file types." It looks like the file is being uploaded (and added to the post if it's added through the editor) but nothing is actually uploaded to the media library.

Requested in Helpshift issue 70628.

**Comment by aforcier** [comment]
Added a note to a more general issue about uploading arbitrary files: #117. Closing.
