### ISSUE TITLE
Drop Open Sans

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#281]
To reflect upcoming changes to the web version, we should drop Open Sans and use system fonts (Roboto) instead.

**Comment by maxme** [comment]
Note: We should use the Merriweather font for user created content (Post title / content), and the default system font for everything else (UI: buttons, labels, Image/Video settings).

**Comment by maxme** [comment]
Ref: https://github.com/Automattic/wp-calypso/pull/3016

**Comment by mattmiklic** [comment]
> Note: We should use the Merriweather font for user created content (Post title / content), and the default system font for everything else (UI: buttons, labels, Image/Video settings).

Exactly right. I think it should be a pretty simple switch, since we can use Roboto at the same size and weight we're currently using Open Sans. Anything that's in Merriweather should be unaffected.
