### ISSUE TITLE
Localize JS strings

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#282]
`Edit` and `Tap to try again` are hardcoded strings in the `ZSSEditor` and cannot be localized. We'll probably need to assign those strings on init, so we can pass a localized String from the native side.

Counterpart issue in the iOS editor repo: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/756

**Comment by aforcier** [comment]
Also `Uploading gallery`, displayed within a [placeholder shortcode](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/a64d3a7097709dc537b0347b8f323622fc8eb847/libs/editor-common/assets/ZSSRichTextEditor.js#L2020).

**Comment by maxme** [comment]
`Uploading...` [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/a64d3a7097709dc537b0347b8f323622fc8eb847/libs/editor-common/assets/ZSSRichTextEditor.js#L865)
