### ISSUE TITLE
Adding a Video to a Post Show Wrong Icon

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Editor-Android#284]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/3322

If you add a video to a post, it shows an image icon. I believe it used to have a video icon. Maybe these days we can get a thumbnail preview of the video?

**Comment by rachelmcr** [comment]
I tested in the new editor (in version alpha-1) and we do use a video icon during upload, but we still don't offer a thumbnail preview of the video.

While uploading:

![2016-03-04 16 42 00](https://cloud.githubusercontent.com/assets/8658164/13533798/050f7f78-e22a-11e5-9aa3-3d2cbc4391d9.png)

After upload finishes:

![2016-03-04 16 43 32](https://cloud.githubusercontent.com/assets/8658164/13533803/08a4b1c6-e22a-11e5-817e-bff71ad2847c.png)

For comparison, here are screenshots of how the iOS editor displays video during/after upload:

![2016-03-04 16 51 17](https://cloud.githubusercontent.com/assets/8658164/13533825/27e28d38-e22a-11e5-88ce-3250e0cf7223.png)
![2016-03-04 16 52 19](https://cloud.githubusercontent.com/assets/8658164/13533832/2b48dfd6-e22a-11e5-8deb-4190ac737744.png)

**Comment by aforcier** [comment]
Opened a new issue for generating thumbnails for uploading videos: #312. The original issue only affects the legacy editor.
