### ISSUE TITLE
markImageUploadFailed must be called with 2 parameters (an id and localized message)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Editor-Android#285]
See [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/9bab5b7db8b6dee3e90fc15feb6e540fcbeae707/WordPressEditor/src/main/java/org/wordpr
ess/android/editor/EditorFragment.java#L998), same kind of problem with `markAllUploadingImagesAsFailed` that must be called with one param (the localized error message) - [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/9bab5b7db8b6dee3e90fc15feb6e540fcbeae707/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L886).

**Comment by aforcier** [comment]
Merged in https://github.com/wordpress-mobile/WordPress-Android/pull/3770.
