### ISSUE TITLE
Failed image upload error message 

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Editor-Android#286]
Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/4075

Should be fixed first: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/285

**Comment by maxme** [comment]
`EditorMediaUploadListener.onMediaUploadFailed` signature must be changed. We probably want to change `MediaEvents.MediaUploadFailed` at the same time (add the error code?).

**Comment by aforcier** [comment]
Merged in https://github.com/wordpress-mobile/WordPress-Android/pull/3770.
