### ISSUE TITLE
Legacy drafts with images are buggy when opened with new editor

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#291]
Steps to reproduce:
1. With the legacy editor, create a new post, insert a local image, and close the post without uploading 
2. Enable the new editor
3. Open the draft post created in step 1
4. The visual editor will show a broken image

Since the legacy editor doesn't upload images until the post is published, the image has a local URL (`src="null" android-uri="file:///storage/emulatored/0/..."`) and the new editor can't read that. We should parse for this and trigger uploads for those images when opening the new editor.

**Comment by maxme** [comment]
Adding images or videos with the legacy editor results in a `<img src="null" android-uri="file:///storage/..."/>` - I tried to add other elements (gallery, youtube videos, ...) we should be fine, that generates either a shortcode or valid html.
