### ISSUE TITLE
Backspacing text that includes whitespace characters can move line text and/or cursor positioning

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Editor-Android#292]
[See video.](https://cldup.com/KInnNYGw0d.mp4)

Tough to describe...rather than a bunch of run-on sentences I'll put some informative bullets.

Problem occurs:
- when line is not first line of text
- first character on line must not be whitespace (a space character, for instance)
- must add a space character to end of line
- after backspacing the space at end of line _then_ backspacing a non-whitespace character

When it reproduces you'll notice the cursor may or may not be positioned incorrectly in the preceding word.

The problem line may or may not jump to the line above, looks as if you deleted a newline character.

Characters in the word you are backspacing may or may not duplicate at cursor position or at the front of the word. For example, backspacing `Test` may result in `TestTesst` on the previous line.

Entering HTML editing then returning guarantees that it will not reproduce within current text.

**Comment by rachelmcr** [comment]
I believe Derek came across this issue in alpha testing here:

> The editor wigged out a bit when I was testing out an ordered list. The line suddenly jumped up an item and I was typing in the middle of a word.

In testing, Val reproduced the issue and found that turning off text correction in Android settings prevented this issue.

**Comment by rachelmcr** [comment]
Mark came across the same issue, with these steps:
1. First, I wrote “Boldly italicize a quote”, selected it, and bolded it
2. Then I selected “italicize” from the sentence and italicized it.
3. Then I selected the whole text again and hit the blockquote button
4. So far, so good! Then I tapped the empty space on the right-side of the blockquote to deselect the text and put my cursor at the end of the sentence, and hit backspace.

Result:

![screenshot_20160229-2005461](https://cloud.githubusercontent.com/assets/8658164/13502847/94a8cfde-e164-11e5-8a4a-a9cd7e68742a.png)

Backspacing two more times resulted in this:

![screenshot_20160229-2005521](https://cloud.githubusercontent.com/assets/8658164/13502856/a0029888-e164-11e5-88a6-b092de8384cc.png)

Tested on a Nexus 6P (device keyboard).

**Comment by maxme** [comment]
Same issue:

https://cloudup.com/cjZjET5Mzj4

**Comment by maxme** [comment]
Same kind of issue with a list:

https://cloudup.com/ixKm0w8ZsDT

**Comment by maxme** [comment]
Described issues above are related to the autocorrect feature. When I disable my virtual keyboard autocorrect, I can't reproduce any of them.
