### ISSUE TITLE
Backspacing uploading media causes editor state loss, users cannot access Settings, HTML view, or save/update

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Editor-Android#297]
Reproduction steps:
- Add local media to post (image or video)
- Backspace to delete the media while it's uploading

Result:
- Cannot access Settings
- Cannot update/save post
- Cannot switch to HTML view

**Comment by aforcier** [comment]
Related (would at least allow the user a way out, though doesn't solve the underlying issue): https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/260
