### ISSUE TITLE
Edit Existing Posts

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#3]
Related to #2. We'll want to edit existing posts too. The current Android editor does not have WYSIWYG editing capabilities for this (just new posts). Existing Android screens for context:

![edit_post](https://cloud.githubusercontent.com/assets/154014/6829780/b33c16bc-d2e3-11e4-9550-7009d08c2e91.png)

![edit_post_2](https://cloud.githubusercontent.com/assets/154014/6829783/b988b25a-d2e3-11e4-82a9-7b43651291d1.png)

/cc @thianhlu

**Comment by aforcier** [comment]
Closing - the new editor supports full WYSIWYG editing experience for new and existing posts.
