### ISSUE TITLE
Getting from Post Creation (keyboard up) to Publish

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#30]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/2283

I've figured out the process for this, but it seems very counter-intuitive to press the back button in order to publish a post that you're working on.  I would wager that we're losing users who get frustrated and leave (I almost did)

**Comment by maxme** [comment]
This is not a problem anymore with the visual editor, the action bar isn't hidden during title or content edition so the user can hit the "Publish" button with the virtual keyboard opened.
