### ISSUE TITLE
Media: Images added from site's media library are always added to the top of the post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#303]
When you add images to a post from the site's media library, they are added to the top of the post instead of at the cursor's current position.

**Steps to reproduce:**
1. Start a new post in the visual editor
2. Type some text at the top of the post
3. Position the cursor below the text and tap the media icon
4. Select "Select from media library" and choose an image

Result: The image appears at the top of the post (with a new line underneath it) and the text you typed below that new line.

**Screenshots:**

Before adding the image:

![2016-02-26 16 51 29](https://cloud.githubusercontent.com/assets/8658164/13358905/6deedcba-dc66-11e5-8279-be14b76f27cc.png)

After adding the image:

![2016-02-26 16 52 19](https://cloud.githubusercontent.com/assets/8658164/13358910/7588c238-dc66-11e5-8e60-1368e5bfab3d.png)

Tested on Nexus 9, Android 6.0.1, alpha-1.

**Comment by aforcier** [comment]
Can't reproduce on Nexus 5X, Nexus 6, or Nvidia Shield, nor on a Nexus 9 6.0.0 emulator. Will try a physical Nexus 9 when I have access to mine.

**Comment by rachelmcr** [comment]
Aha! I narrowed this down to having `Don't keep activities` enabled in Developer options.
