### ISSUE TITLE
Add support for hardware keyboard shortcuts

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#308]
Mark brought this up in alpha testing on his Nexus 6P:

> Things went smoothly with a keyboard plugged in, though I found it a tad frustrating that cmd+b didn’t bold text. Is that possible on Android?

It would be great to support common formatting shortcuts for users who use hardware keyboards, if that is possible and sane. (However, we might want to wait to see the results of #180 to decide if it should be a priority.)

**Comment by aforcier** [comment]
I seem to remember this working in the past - does Ctrl + key (instead of cmd) work? I don't have a hardware keyboard with me at the moment to test.

**Comment by thingalon** [comment]
_facepalm_

Yep, ctrl+b does work, which is probably more in-line with the "official" Android keyboard shortcuts than my mac-trained fingers can manage. 

Sounds like this is a non-suggestion.

**Comment by aforcier** [comment]
Great! I was worried I'd somehow axed keyboard shortcuts for a moment there. :wink:
