### ISSUE TITLE
Media: Backspacing to remove failed media upload leaves behind extra html

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#313]
If an image upload fails, you can backspace to remove the failed image. However, that only deletes the `img` tag, leaving behind extra html (`span` and `progress` tags) related to the failed upload. For example:

```
<span id="img_container_1457444268500" class="img_container largeFail failed" data-failed="Tap to try again!"><progress id="progress_1457444268500" value="0" class="wp_media_indicator failed" contenteditable="false"></progress>
</span>
```

As a result, the cursor doesn't show up properly, and any text you type after removing the image ends up inside the `span` tags so the failed upload overlay appears over it.

**Steps to reproduce:**
1. Start a new post and type some text
2. Turn off the internet connection on your device (to ensure a failed upload)
3. Upload an image to your post
4. After the upload fails, place your cursor after the image and backspace to remove it.
5. Check the HTML view of the post (to see the leftover html) and/or type some more text (to see the effect of that leftover html).

Tested on Nexus 9, Android 6.0.1, app version alpha-2.

**Comment by aforcier** [comment]
Good news! I have an upcoming PR that fixes https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/297, that also fixes this issue. I'll close this when the PR lands/is tested. That should make it into alpha-3.

**Comment by rachelmcr** [comment]
Woohoo! That was easy. :)

**Comment by tonyr59h** [comment]
Addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/3887, closing.
