### ISSUE TITLE
Cursor jumps to top right when switching from HTML to Visual mode

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#314]
When switching between HTML and Visual modes, I expect the cursor to either stay where it is in the post or jump to the very beginning of the post.

Instead, if the cursor isn't on the first line of text when you switch from visual to html mode, it will appear in the top right corner when you switch back to visual mode.

**Steps to reproduce:**
1. In the visual editor, type some text, hit return to start a new line, and type more text.
2. With the cursor on the second line of text, switch to the html mode.
3. Switch back to the visual mode.

Result: The cursor appears in the top right corner of the editor. If you start typing without repositioning the cursor, it will place the text at the beginning of the line you were on before leaving the visual editor (even if that wasn't where the cursor was placed before switching between visual and html).

**Screenshot** (after switching from visual to html and back to visual):

![2016-03-08 18 14 24](https://cloud.githubusercontent.com/assets/8658164/13611368/14e65498-e55a-11e5-9fae-8f47e259ed3c.png)

Tested on Nexus 9, Android 6.0.1, app version alpha-2.

**Comment by aforcier** [comment]
Possibly related to #302 (this should be tested once a fix for #302 is added).
