### ISSUE TITLE
Don't unconditionally auto-refresh remote data on configuration change

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#32]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/2214

Behavior when changing orientation should be consistent. Here's a list of screens I've checked and what network calls they make on configuration change:

| Activity | Behavior |
| --- | --- |
| Posts/Pages | always auto-refresh |
| Select Post Categories (inside Edit Post Settings) | no auto-refresh |
| Comments | no auto-refresh |
| Media | no auto-refresh |
| Reader | varies, see below |
| Notifications | no auto-refresh |
| Stats | no auto-refresh |
| Stats - Single Post Details | no auto-refresh |
| Stats - View All | no auto-refresh |
| Themes | no auto-refresh |
| Manage Blogs (Settings > Show/hide WordPress.com blogs) | no auto-refresh |

Reader details:
- Will always auto-update /read/menu and read/following/mine.
- Will also auto-update /read/liked or /read/following if those are selected from the menu.
- Will auto-update selected blog if 10 minutes have passed since last refresh.

**Comment by maxme** [comment]
This is more a Post list issue than an editor issue.
