### ISSUE TITLE
Backspacing a list item doesn't delete it when it's the first thing in a post

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Editor-Android#331]
Demo: https://cloudup.com/cqX7UNM7ct1

Note: Keyboard suggestions are disabled but this happens with suggestions enabled.

**Comment by aforcier** [comment]
@maxme: I think this has been fixed, could you try to reproduce it on your device?

**Comment by maxme** [comment]
Can't repro on 1.1!🎉
