### ISSUE TITLE
special characters getting URL encoded on switching between HTML and Visual Editor API 15

### ISSUE THREAD

**Issue by hemantparmar23** [wordpress-mobile/WordPress-Editor-Android#335]
Characters like Space getting converted to %20, inverted commas converted to %22 and so on ..
Tested on Emulator API version 15.

**Comment by maxme** [comment]
I guess this will be fixed by #357 
BTW, we're going to drop support for API14 and 15. min requirement will be API 16.

**Comment by maxme** [comment]
Won't fix. API 16 will be required.
