### ISSUE TITLE
Page Options: Add the option to set the parent of a Page

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#34]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/2110

Currently in neither the iOS or Android app are you able to set the parent attribute of a Page.
This is a feature request to have that added in a future version.

**Comment by rachelmcr** [comment]
A user recently requested this feature again in an Android app review.

**Comment by aforcier** [comment]
This is related to WPAndroid's post settings and not the editor itself - migrating back to that repo.
