### ISSUE TITLE
Weird behavior with links at the end of the line in blockquotes

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#345]
If you add a link to the end of a line in a blockquote, the link is pushed to a new line. Creating a new line after the link creates a new, separate blockquote.
### Steps to reproduce
1. Start a new post in the visual editor.
2. Start a blockquote with regular text.
3. Add a link at the end of the line of text. Result: The link is moved to a new line.
4. Hit enter to start a new line. Result: The new line starts in a new blockquote.

I tried using the link button to create the link and link text, and I tried typing the link text and selecting it to create the link, with the same results.

Screencast: https://cloudup.com/c7nA73baZ1E

**Comment by rachelmcr** [comment]
To give an example of a real-life use case, I often end blockquotes with the name of and a link to the source (within the blockquote) and would run into this bug every time I do that.

**Comment by aforcier** [comment]
Probably introduced by https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/334, needs testing.
