### ISSUE TITLE
Content loss when switching to HTML mode on older/slower devices

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#347]
Possibly the only cause of content loss tracked in https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/47. This is caused by a race condition: the `CountDownLatch` `await` inside `getTitle()` and `getContent()` seems to be holding up the editor from receiving the title/content strings from JavaScript.

Confirmed on Nexus S API16, and on several emulators.

**Comment by maxme** [comment]
I'm pretty sure this is the same root cause as in https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/309
