### ISSUE TITLE
Line breaks are removed on upload on API16

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#350]
On `API16` (both on an emulator and the Nexus S), line breaks are stripped when extracted from the ZSSEditor (autosave in WPAndroid, switching to HTML mode, and publishing).

For example, text like this:

```
Line 1

Line 2
```

becomes

```
Line 1Line 2
```

when published.

**Comment by aforcier** [comment]
Note: This wasn't introduced with the `p`>`div` switch, I checked out an earlier commit and this bug still occurs when using `p` tags.

**Comment by maxme** [comment]
I found the culprit: it's [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/2daf87ed6542667c62a39bc2ea5225fd2226a14b/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorWebViewAbstract.java#L61-L61), the returned callback data, via the url can't contains `\n`, that's also why it happens on API 16 only.

**Comment by aforcier** [comment]
Fixed in #357.
