### ISSUE TITLE
Fetch/cache tag list and add an autocomplete element to edit post tags list

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#36]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1999

We could probably reuse the UI element made for suggestion `SuggestionAutoCompleteText`. @oguzkocer

**Comment by maxme** [comment]
Note: this is almost done in this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/2415

**Comment by maxme** [comment]
Implemented and merged wordpress-mobile/WordPress-Android#2415
