### ISSUE TITLE
Post is blank after an error during the upload

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#38]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1929

From a user:

> I just tried to upload a post to WordPress using the latest version of the
> Android app, but instead it has deleted the entire content on the post.
> 
> The progress bar showed it had uploaded all the images, then at the last
> second it gave an error saying missing peer certificate or something like
> that. When I opened it again in the WordPress App, it was blank! Only the
> post settings (keywords/categories etc) remain.
> 
> I was able to upload a different post 5 min before and I have uploaded one
> since as well (5 min after this happened).

I checked on the server and the post is there, but it's blank. Only categories are there.
Pictures are on the server, but not attached to any post.

Not sure how this could happen, may worth to take a closer look at the posting service.

**Comment by maxme** [comment]
Migrating back to WPAndroid.
