### ISSUE TITLE
Show more tags in the visual editor

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Editor-Android#382]
Currently, more tags aren't displayed at allin the visual editor. Eventually we want to re-implement the more button for the visual editor, perhaps as part of an ['advanced' format bar](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/371), but in the meantime we should add some sort of visual affordance for the more tag. This is what the Calypso visual editor uses:

<img width="731" alt="screen_shot_2016-05-05_at_7 44 20_am" src="https://cloud.githubusercontent.com/assets/9613966/15426823/0b394cbe-1e5f-11e6-9f15-5480b7b51c73.png">

**Comment by rachelmcr** [comment]
While we're at it, it would be nice to visually represent page breaks, too. (A user mentioned this in a recent iOS app review.) Page breaks can be added with `<!--nextpage-->` in the HTML editor.

This is what the Calypso visual editor uses for page breaks:

![screen shot 2016-05-27 at 11 28 15 am](https://cloud.githubusercontent.com/assets/8658164/15605481/22263f64-23fe-11e6-82ed-4f0c793bc6d7.png)

I can open this as a separate issue if it's beyond scope here.
