### ISSUE TITLE
Legacy: Image settings not saved when image is uploaded to a post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#391]
This bug only affects the legacy editor, not the visual editor.
### Expected behavior

I expect to be able to add an image to a post, edit the image settings, and have the image settings retained.
### Actual behavior

I add an image to a post (upload from the device or capture a new image), edit the image settings, and save/publish the post. The image meta (title, caption, alignment) is lost.

If I also choose in the image settings to set the image as the featured image for the post, the image is not set as the featured image for the post. (And it is always included in the post content, regardless of that image setting.)

The image settings work as expected if the image is added from the site's media library instead of being captured or uploaded from the device.
### Steps to reproduce
1. Open the WordPress app
2. If the visual editor is enabled, go to Me > App Settings > uncheck "Show visual editor"
3. Go to your site dashboard and open the editor to start a new post
4. Tap the add media button in the format bar
5. Upload or capture an image to add to the post
6. Tap the image to open the image settings
7. Add a title, caption, horizontal alignment, and width
8. Optional: Check the option "Use as featured image"
9. Optional: Check the option "Include image in post content"
10. Tap "OK" to save image settings
11. Publish the post

Result: The image is included in the post content, but none of the image settings (title, caption, alignment, width) are set, and the image is not set as the featured image for the post.

You can repeat the steps above but add the image from the site's media library (step 5) and the image settings will save as expected.

**Comment by aforcier** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/issues/4161.
