### ISSUE TITLE
Can't edit image settings for an unlinked image

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#392]
### Expected behavior

After adding an image to a post, I expect to be able to tap the image to edit the image settings.
### Actual behavior

If an image isn't linked, tapping on the image to edit the image settings either does nothing (no edit overlay appears) or removes the image from the post.
##### Image added from media library (first thing in the post)
1. Open the WordPress app
2. Make sure the visual editor is enabled (Me > App Settings > check "Show visual editor")
3. Go to your site dashboard and open the editor to start a new post
4. Tap the add media button in the format bar
5. Choose "Select from media library"
6. Select an image from the site's media library
7. In the editor, tap the image

Result: The image added from the media library isn't linked, and tapping it has no result.
##### Image uploaded to post
1. Open the WordPress app
2. Make sure the visual editor is enabled (Me > App Settings > check "Show visual editor")
3. Go to your site dashboard and open the editor to start a new post
4. Tap the add media button in the format bar
5. Choose "Select a photo from gallery"
6. Select an image from the device
7. In the editor, after the image finishes uploading tap the image to bring up the edit overlay
8. Tap again to open the image settings
9. In the "Link to" field remove the URL (so the image isn't linked to anything)
10. Tap Save in the top right to save the image settings
11. In the editor, tap the image

Result: The image is removed from the post. (This is also the result if you add an image from the media library and it isn't the first thing in the post, e.g. there is some text at the top of the post.)

**Comment by maxme** [comment]
resolved by https://github.com/wordpress-mobile/WordPress-Android/issues/4157
