### ISSUE TITLE
Auto-linked url are not editable

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#41]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1742

Steps:
- Share a link to the WP app (e.g. Chrome -> Share -> WP)
- The link appears in the Content TextEdit but can't be edited by tapping the "link" icon.

**Comment by maxme** [comment]
On the visual editor, links are not auto created from the url when shared from other apps - we might want to fix that.
