### ISSUE TITLE
Posts list onSelect post animation is weird

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#45]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1614

It seems a fade animation is mixed with a slide in animation

**Comment by rachelmcr** [comment]
This post list/editor layout is no longer used, and this animation is no longer an issue. (Tested with Nexus 9, Android 6.0.1, app v. alpha-3.)
