### ISSUE TITLE
Image upload breaks after pressing back on the post editor during upload

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Editor-Android#453]
If you back out of a post while an image is uploading, the post preview shows it as partially uploaded even though it never actually completed. If it fails and you back out, it shows the “try again” arrow even though you can’t click on it.

**Comment by rachelmcr** [comment]
Related issue: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/264

**Comment by aforcier** [comment]
Fixed with [async media](https://github.com/wordpress-mobile/WordPress-Android/pull/6447).
