### ISSUE TITLE
Image Settings: Changes to image settings in the editor can't be saved

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#454]
### Expected behavior

After adding an image to the editor, you can tap the image to edit the image settings. After changing the image settings, you should be able to save those changes and return to the editor.
### Actual behavior

No "Save" button appears in the image settings, so the changes can't be saved. The only option is to cancel the changes and return to the editor without saving.
#### Screenshot

![2016-09-30 20 14 44](https://cloud.githubusercontent.com/assets/8658164/19035583/42d13d76-8962-11e6-844b-0a1f678a651b.png)

**Comment by maxme** [comment]
This is a weird one, could be Android 7.0 only (just tested on a 6.0 and couldn't reproduce).
