### ISSUE TITLE
Use "em" and "strong" tags instead of "i" and "b" tags for italics

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Editor-Android#459]
Currently, when you add bold and italic formatting to text in the visual editor, it is rendered in the HTML as `b` and `i` tags.

However, in the Calypso web editor, bold and italic formatting are rendered as `strong` and `em` tags. We should update the app's editor to match.

h/t @lancewillett for sharing a link to this post explaining more about why this is important for localization: https://www.w3.org/International/questions/qa-b-and-i-tags

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-28

**Comment by aforcier** [comment]
@rachelmcr I think this is a dup of https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/206

**Comment by rachelmcr** [comment]
Oops, so it is. I missed that while searching; closing this as a dupe!
