### ISSUE TITLE
Quick Post Status / Aside

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#46]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1556

The app already has quick post capabilities for photo and video.
How about a quick post capability for a status / aside post ?
This would give us the ability to post quick tweet-like things.
I would hope that the status / aside post format would be automatically set.

The Twitterify plugin automatically creates wordpress tags by entering hashtags.

**Comment by maxme** [comment]
The App now have a way to specify the default post format, I think it's enough - we could have a Quick Post widget that selects the Status post format automatically, but that feels like an overkill and a completely buried feature (widgets are not easily accessible).
