### ISSUE TITLE
Some users lose content they're working on

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#47]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1543

From a user:

> When sharing multiple photos to a post from the G+ gallery, several posts got stuck in local draft. I had to edit and publish again. Every post except one successfully published on the second attempt. One lost all content, including several images.

We also have comments on the Play Store from users who lost their work and can't find a local draft version. Seems only related to local drafts.

This is going to be hard to reproduce...

**Comment by maxme** [comment]
I fear this could to be an even bigger problem with the Webview, this should be thoroughly tested (with "don't keep activities" enabled)

**Comment by maxme** [comment]
I'm experiencing a lot of (small) content loss with the visual editor, but **only on emulators**
Steps:
1. edit using the visual mode, add a few words.
2. immediately switch to HTML mode.
3. notice the latest words disappeared.

**Comment by aforcier** [comment]
It would be nice to test this on an old and slow ~`API 16` device if we find one.

**Comment by aforcier** [comment]
Experiencing content loss on an API16 Nexus S when switching from visual to HTML mode in the demo app. It looks to be a race condition issue; the `CountDownLatch` `await` seems to be holding up the editor from receiving the title/content strings from JavaScript.

**Comment by maxme** [comment]
This should not happen after the merge of https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/351 and https://github.com/wordpress-mobile/WordPress-Android/pull/3976
