### ISSUE TITLE
Gallery doesn't work well on self-hosted sites

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#52]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1406

Some of the features in "Gallery Settings" are available to WordPress.com sites only. The app doesn't check if the current blog is Self-Hosted or not when creating that screen, resulting in unexpected result on self-hosted blogs.
For example if the user select type = Slideshow.

Ref: http://android.forums.wordpress.org/topic/slideshow-gallery-seems-not-to-work?replies=1

http://codex.wordpress.org/The_WordPress_Gallery

**Comment by rachelmcr** [comment]
This is still an issue in the new editor. On a self-hosted site without Jetpack, you still see Jetpack/WordPress.com-specific gallery options with no warning that the gallery type won't work on the self-hosted site.

Tested on Nexus 9, Android 6.0.1, alpha-4.

**Comment by aforcier** [comment]
Migrating back to WPAndroid since it's a WP media issue.
