### ISSUE TITLE
Disappearing images in post editor after activity is closed

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#56]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1314
1. Enable `Don't keep activities` option in device settings.
2. Open app, tap new post button.
3. Add an image from the device gallery. Observe it is added to the post.
4. Add another image from the device gallery. Observe that the first image is now gone.

**Comment by rachelmcr** [comment]
I tested this issue with the above steps in the new editor (Nexus 9, Android 6.0.1, app v. alpha-5), and I could not reproduce it. Both images appear in the editor. Closing as resolved.
