### ISSUE TITLE
See old preview after posting

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#58]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1250
- start writing a post.
- exit out and save draft when prompted.
- go back to the post and see preview.
- click edit.
- add some more text.
- hit save / publish
- sent back to preview for a second and see old preview from the earlier save.
- Panic!
- sent back to post list and see that the post did actually publish with the new text

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. After the post is updated/published, I am sent back to the preview and the preview refreshes to show my latest changes.

Tested on Nexus 9, Android 6.0.1, alpha-4.
