### ISSUE TITLE
Post editor, keyboard not dismissed when adding a picture

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#59]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1178
1. Create a new post.
2. Add a picture.
3. Delete this picture from the post.
4. Add a picture, this time keyboard isn't dismissed, it stays on top of the Gallery image picker.

**Comment by aforcier** [comment]
Does not occur in the visual editor.
