### ISSUE TITLE
Post options/settings

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#6]
I am assuming we will be updating the post options/settings UX as we address the new post/page workflow. Here is the existing screen:

![screen shot 2015-03-30 at 10 21 54 am](https://cloud.githubusercontent.com/assets/154014/6899544/d3fc0fb0-d6c6-11e4-96dd-5114cd8076e0.png)

/cc @thianhlu

**Comment by aforcier** [comment]
Note: the current editor labels the button 'Post Settings' even when editing pages - this should be changed.

**Comment by aforcier** [comment]
The legacy editor has a bottom bar with a button for post settings (which only appears when editing the title or when the keyboard is dismissed):

![wpandroid-post-settings-legacy](https://cloud.githubusercontent.com/assets/9613966/9497417/847ae318-4c1d-11e5-9704-08432888a909.png)

Shall we replace it with an action bar icon, like on iOS?

![iOS-post](https://cloud.githubusercontent.com/assets/154014/6829061/24b44972-d2df-11e4-8101-563023b44d43.png)

cc @thianhlu, @bummytime

**Comment by thianhlu** [comment]
Yeah lets move it to the top

**Comment by aforcier** [comment]
![6-settings-button](https://cloud.githubusercontent.com/assets/9613966/9521689/038b75b2-4cd9-11e5-8813-1263ea6607a5.png)

How is that @thianhlu?

**Comment by thianhlu** [comment]
:+1:
