### ISSUE TITLE
Images shared to a post from media library are too large

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#60]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1151
1. Share a single image to a post from the media library.
2. Observe that the image is too large and covers the majority of the editing area.

**Comment by rachelmcr** [comment]
I wasn't able to reproduce this issue with the new editor (Nexus 9, Android 6.0.1, app v. alpha-5).

Images added from the media library (either via My Sites > Media > long tap on image > edit icon, or directly in the editor via Add Media > Select from media library > tap to select image) are always added with the `size-full` class and display at the full width of the editor (not too large in the editor or in the published post).

Closing as resolved.
