### ISSUE TITLE
Hide or disable share button in the edit post bottom toolbar when status != published/scheduled

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#61]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1137

Currently shows an error popup when you tap the share.

Could be done with #1126.

**Comment by maxme** [comment]
This share button has ceased to be.

**Comment by aforcier** [comment]
It's expired and gone to meet its maker.
