### ISSUE TITLE
Internationalization needed in MediaGalleryAdapter

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#64]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1083

Check bindView in: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/src/org/wordpress/android/ui/media/MediaGalleryAdapter.java

There's strings like "Dimensions: " that need to be added to the strings.xml file to support internationalization.

**Comment by rachelmcr** [comment]
I confirmed that the strings in MediaGalleryAdapter are now internationalized and translatable; closing as resolved.
