### ISSUE TITLE
Submitting post before video downloads results in no video

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#69]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/929
- Create a new post
- Insert a video from your gallery
- Submit the post as soon as the "Downloading media" toast appears

Post will be uploaded without the video.

**Comment by rachelmcr** [comment]
This is no longer an issue in the new editor. While uploading media, the Publish action is blocked (with a message "You are current uploading media"). This prevents you from publishing a post until the media has finished uploading.

Closing as resolved in the new editor.

Tested on Nexus 9, Android 6.0.1, alpha-4.
