### ISSUE TITLE
Editor onboarding

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#7]
On, iOS we considered the first run experience for both new users and existing users seeing the new editor for the first time.
- Tooltips: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/165
- What's New: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/466

Assuming we may do something similar for Android.

/cc @thianhlu

**Comment by bummytime** [comment]
Ref #145

**Comment by bummytime** [comment]
![ev8lwojvv7](https://cloud.githubusercontent.com/assets/154014/8260200/a5f2f8f8-1687-11e5-84de-2909320a2455.png)

**Comment by aforcier** [comment]
With the editor preview getting dropped in the new editor, we might want to add something to onboarding like “now, preview as you write with the new visual editor” for a smoother transition to a preview-less editor.

**Comment by maxme** [comment]
If we want to show a message when the user first opens the new editor, we might want to reuse the code/design of what was done for the Stats widget: https://github.com/wordpress-mobile/WordPress-Android/issues/3658

**Comment by aforcier** [comment]
From discussion with @maxme, since the rest of the editing flow hasn't really changed, the tooltips aren't necessary for the editor.

For the 'What's New' message, we can use the Stats implementation Maxime mentioned, re-using the graphic/wording from iOS: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/519#issuecomment-73598631.

cc @mattmiklic

**Comment by maxme** [comment]
I vectorized this iOS image and changed the colors to keep it consistent with the Stats promo dialog. Here is a screenshot in situ

![screenshot-2016-03-02_20 29 43 293](https://cloud.githubusercontent.com/assets/40213/13472637/15f014d0-e0b6-11e5-964b-a09a8da49c0e.png)

Pencil border colors look weird - @mattmiklic can you help me with that? SVG source is here: https://cldup.com/uI3GXFyyfOu/Ls10vH.svg - image must be 280 x 120

**Comment by mattmiklic** [comment]
The illustration we used for the new editor on iOS is a little out of date compared to our current icons. How about we re-use this illustration?

Mockup:
![mockup](https://cloud.githubusercontent.com/assets/1396552/13502339/94f2a61c-e138-11e5-8d73-b5c237313c26.png)

SVG:
https://cldup.com/s8uzfa-DrH.svg

**Comment by maxme** [comment]
> How about we re-use this illustration?

:heart:
