### ISSUE TITLE
When opening a post with a <br> tag the save dialog appears even when no modification has been made

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#70]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/923

`Post.hasChanges()` fails because `post.description != other.description` (we should normalize description before the equality check)

https://cloudup.com/cXEMq8Emvtl

**Comment by rachelmcr** [comment]
I re-tested this issue in the new editor, and it is still an issue there. If the post has a `<br>` tag, opening it in the editor and then leaving the editor results in local changes to the draft even if no changes were made.

Tested in Nexus 9, Android 6.0.1, alpha-4.

**Comment by aforcier** [comment]
Can no longer reproduce this, tested on Nexus 5X, Android 6.0.1, WPAndroid 5.5.
