### ISSUE TITLE
Existing posts are geotagged when edited

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#75]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/870

If geotagging is disabled when you create and publish a post, if you edit that post after re-enabling geotagging then a location will show for it in post settings. Shouldn't geotagging only apply to new posts?

**Comment by rachelmcr** [comment]
I tested this issue in the new editor with the following steps:
1. Select a site and make sure "Enable Location" is disabled in the settings
2. Create a new post and confirm that no location is set
3. Turn on the "Enable Location" setting for the site
4. Create another new post and confirm that a location is set
5. Edit the first post and update it

Result: No location was added to the edited post, as expected.

Closing this issue as resolved.

Tested on Nexus 9, Android 6.0.1, alpha-4.
