### ISSUE TITLE
Posting: change EditText hint when it has the focus

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#76]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/826

In the post editor, when you tap the editor to start typing your post the hint still includes "tap to add text and media."

![device-2014-02-06-110045](https://f.cloud.github.com/assets/3903757/2100638/a332a610-8f4a-11e3-9e67-d2485b91dc4d.png)

**Comment by rachelmcr** [comment]
The new editor uses the text "Share your story here..." in the post body, which still works even when it has focus. Closing as resolved for the new editor.

![2016-03-21 19 09 40](https://cloud.githubusercontent.com/assets/8658164/13930857/9223efcc-ef98-11e5-8204-065fe2e14201.png)

Nexus 9, Android 6.0.1, alpha-4.
