### ISSUE TITLE
Weird UX for post categories

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#77]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/729

When selecting a category for a post, if a category is already checkmarked and you try to checkmark Uncategorized, the Uncategorized checkmark disappears right after you add it. I understand why this is being done, but it's a weird user experience.

**Comment by rachelmcr** [comment]
I tested and reproduced this issue on Nexus 9, Android 6.0.1, alpha-4 (new editor).

**Comment by aforcier** [comment]
Migrated back to WPAndroid.
