### ISSUE TITLE
Only new mobile app users should see the new editor

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#8]
With the iOS editor, we implemented a way to "turn on" the new editor for selected users. Thus allowing us to have a controlled rollout of this new feature. We will need to do a similar thing on Android...e.g.
- People who sign up for WP on iOS app will be using the new Editor for New Posts and Editing Posts
- All existing Android users and people who already had a WP account that just installed the Android app will be using the existing editor.

Ref: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/126

**Comment by bummytime** [comment]
On iOS we used a url scheme to (secretly) enable the editor. We will need to do a similar concept here.

ref: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/143

**Comment by maxme** [comment]
I'll to use the same URI scheme/host/params: [wordpress://editor?available=1&enabled=1](wordpress://editor?available=1&enabled=1) 

Sample link on: https://bia.is/wpbeta/2016/02/02/wordpress-scheme/

**Comment by maxme** [comment]
Fixed via https://github.com/wordpress-mobile/WordPress-Android/pull/3689
