### ISSUE TITLE
Filter Posts/Pages by status

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#84]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/564

A user requested that the post list be filterable by post status, similarly to #58

**Comment by rachelmcr** [comment]
Filtering the post list by status is part of this Calypso Posts & Pages Punch List: https://github.com/wordpress-mobile/WordPress-Android/issues/2793

Closing this issue since it's being tracked there.
