### ISSUE TITLE
Re login with different user - shows posts from last user

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#86]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/383

Hello,

I have 2 users, each one with his posts (private posts), when i switch-login from one to the other, I see the posts from the last user. This is solved if I refresh, but where can I set an automatic refresh for the current user at login (both in 'view admin' and 'my posts')?

I browsed the issues list, but found nothing of the sort.

Many thanks :)

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. Logging out and back in with another account refreshes the site and post lists so the new user only sees the posts they should see for their account.

Tested on Nexus 9, Android 6.0.1, alpha-4.
