### ISSUE TITLE
Support both the legacy and new editor simultaneously

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#9]
On iOS we had a switch in the app settings: 

![scaled screen shot 2015-03-30 at 10 40 59 am](https://cloud.githubusercontent.com/assets/154014/6899969/5688a658-d6c9-11e4-912e-3bd5e90a13ee.png)

Having this helped facilitate:
- Beta testers
- Initial rollout of the new editor (#8)
- Supporting users that wanted to continue using the old editing experience 

This is something we could implement on the app settings screen in a similar way to pin lock:

![screen shot 2015-03-30 at 10 44 22 am](https://cloud.githubusercontent.com/assets/154014/6900073/c39f81a8-d6c9-11e4-8d1e-e5d79a91e946.png)

**Comment by aforcier** [comment]
Implemented in this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/2870
