### ISSUE TITLE
Add a way to stop Media file uploading

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#90]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/318

We need to add a way to stop pictures uploading in "Media".
I was in "Media", and selected a picture to upload on the blog. Uploading started but I was in an area with poor coverage and it took 10 minutes without the possibility to stop it. 

Also, media library was unresponsive while uploading due to https://github.com/wordpress-mobile/WordPress-Android/issues/226.

**Comment by rachelmcr** [comment]
The new editor allows you to tap on uploading media, bringing up a dialog to stop the upload:

![2016-03-21 14 33 02](https://cloud.githubusercontent.com/assets/8658164/13921887/f6a250dc-ef71-11e5-997c-db1ea5d0b183.png)

Closing as resolved in the new editor. Tested on Nexus 9, Android 6.0.1, app v. alpha-4.
