### ISSUE TITLE
Very long titles should be truncated in the Post list

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#91]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/252

![device-2013-11-04-103603](https://f.cloud.github.com/assets/40213/1463763/67299c7c-4536-11e3-894a-d2668a5b750f.png)

**Comment by rachelmcr** [comment]
I checked in app v. alpha-4 and the post list now truncates the post title after 3 lines (both vertical and horizontal orientations).

Vertical:
![2016-03-21 14 38 00](https://cloud.githubusercontent.com/assets/8658164/13922098/bbeaa7d6-ef72-11e5-9893-6c112d7e48e9.png)

Horizontal:
![2016-03-21 14 38 04](https://cloud.githubusercontent.com/assets/8658164/13922104/bfccf9d0-ef72-11e5-8879-89d859c5c9af.png)

Closing as resolved.
