### ISSUE TITLE
Post: On a slow connection, app doesn't seem to do anything while uploading image.

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#92]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/231

Create a new post and include an image from the phone.  Publish the post.
Notice the toast informing you that the post is being uploaded. 
On a slow connection, once the toast is gone there is a fair amount of time before the refresh spinner starts animating (because the list is being refreshed maybe?).  Probably the spinner should be animating from the start of the file upload.

**Comment by rachelmcr** [comment]
This is no longer an issue: The editor displays a progress bar in-editor as the image uploads, and prevents publishing while the upload is in progress. After publishing, the post list immediately shows an "uploading" message for the post being published until it finishes. Even on a slow connection this worked for me.

Tested on Nexus 9, Android 6.0.1, alpha-4.
