### ISSUE TITLE
Media: Tapping back from an item detail accessed via search does not take you back to search.

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#97]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/214

On the media feature:
Access the search feature via the actionbar menu.
Enter a search term to view a subset of the media items.
Tap on of the items to view its detail
Tap the back button. 
Instead of viewing the search results you're back on the main list. 

2.5 beta 4
Nexus 4 / 4.3

**Comment by rachelmcr** [comment]
I can reproduce this in alpha-4, in the Media section of the app. However, since this isn't really an editor issue (it's an issue in the Media section, not within in the editor) is this the right repo for the issue?

Nexus 9, Android 6.0.1, alpha-4.

**Comment by aforcier** [comment]
Migrating back to WPAndroid as it's a Media section issue.
