### ISSUE TITLE
Media: Uploading media has not title on the detail screen

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#98]
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/211

Go to the Media screen and capture a new photo. 
While the photo is uploading, tap it to view the detail.
The title is blank. 

2.5 beta 4
Nexus 4 / 4.3

**Comment by rachelmcr** [comment]
I re-tested this issue in the Media section and couldn't reproduce the problem. Tapping on the photo while it is uploading shows the file name, a blank file type, and the date added (no title). The option to edit the title only appears after the photo finishes uploading.

In the editor, tapping on the photo while it is uploading only gives the option to stop the upload. After it finishes uploading, you can tap to edit the image settings. In this case there isn't a title set on the image yet, but that is consistent with the web editor which gives a file name but not a title attribute for uploaded images.

Nexus 9, Android 6.0.1, alpha-4.
